"""Group multi-disk sets and plan/write M3U playlists for the libretro PUAE core.

PUAE m3u format (verified against https://docs.libretro.com/library/puae/ and the
parser ``dc_parse_m3u`` in libretro-uae ``libretro/libretro-dc.c``):

* Plain text, one disk per line, in disk-control order. Paths may be absolute or
  relative to the m3u's directory. Each line is whitespace-trimmed, so names
  with leading/trailing spaces can't be referenced.
* ``#SAVEDISK:<VolumeName>`` adds a blank save disk (volume name optional).
* ``#COMMAND:`` is special; every other line starting with ``#`` is ignored, so
  our first-line ownership marker ``# Generated by simple-rom-organiser`` is safe.
  A disk path that itself starts with ``#`` is written as ``./#...``.
* ``path|Label`` sets the disk-control label; the split is at the *first* ``|``,
  so paths containing ``|`` can't be referenced (``safe_filename`` removes them).
* ``archive.zip#member.adf`` / ``.7z#`` selects one disk in a multi-file archive;
  single-file archives can be referenced directly. ``.rar`` is not supported.
* PUAE loads at most 20 entries (``DC_MAX_SIZE``).

TOSEC multi-disk naming (as found in "Commodore Amiga - Games - [ADF]"
TOSEC-v2025-01-30, 34410 roms, 19183 carrying a disk token)::

    Title (Year)(Publisher)[(other)](Disk X of Y)[(label)...][flags]

* The only disk token form in that DAT is ``(Disk N of M)``; ``(Disk A of B)``
  letters and ``(Side X of Y)`` are accepted as well. A bare ``(Disk 1)`` without
  a total never appears as the media token (only as a *label*, e.g.
  ``(Disk 2 of 3)(Disk1)``), so it is not treated as one.
* Zero or more ``(...)`` groups directly after the token are the per-disk media
  label (``(Boot)``, ``(Program)``, ``(Data Disk)``, ``(A)``, ``(Reel 1)``, ``(Disk1)``
  ...). They are removed from the grouping key and used as the m3u label.
* Dump flags ``[...]`` are **per disk**: a trainer, bad dump or hack usually only
  touches the disk it modified, e.g. ``X (Disk 1 of 2)[cr CSL][t +12 GOD]`` goes
  with ``X (Disk 2 of 2)[cr CSL]``. Grouping on the full name (flags included)
  completes only ~14% of the real DAT's sets, and TOSEC lists only the disks that
  changed between versions, so sets are built *slot by slot* (:func:`resolve_slots`):

  1. Candidates are grouped by game *identity* (``tags.identity_key``: title without
     version/date, publisher, region, language, edition), so versions of one game share a group.
  2. Every disk 1 is an *anchor* with flag set ``F``. For each slot ``i`` the set takes the
     newest disk ``i`` the user has that is compatible with ``F`` and not newer than the anchor.
     ``ABC Monday Night Football v1.1 (1991)(Data East)(US)(Disk 1 of 3)[cr SR]`` therefore
     gets ``... (1990)(Data East)(US)(Disk 2 of 3)`` and ``(Disk 3 of 3)``, which carry no version.
     Dump flags ``[cr ..]``, ``[t ..]``, ``[h ..]``, ``[a]``, ``[b ..]`` ... outside ``F`` make a
     disk incompatible (different cracks are never mixed) unless they *generalise* a flag of
     ``F`` (``[cr]`` / ``[cr Galahad]`` go with ``[cr CSL]`` / ``[cr Galahad v1]``); notes such
     as ``[!]``, ``[bootable]``, ``[cp manual code]``, ``[docs]``, ``[HD]`` are neutral.
  3. Callers pass only eligible disks: excluded variants (pre-release, bad dumps, ...) are
     never borrowed from.

  Sets that select the same files are merged, incomplete sets contained in another set are
  dropped, a group without any disk 1 yields one incomplete pseudo-set. There are no
  best-effort sets: a set is complete only when every slot 1..N is filled.
* M3U name = anchor title + the anchor's dump flags + the neutral flags shared
  by every chosen disk, e.g. ``ABC Monday Night Football v1.1 (1991)(Data East)(US)[cr SR].m3u``
  or ``'Allo 'Allo! Cartoon Fun! (1993)(Alternative)[cr CSL][t +12 GOD].m3u``. When the
  same name stands for sets with different disk counts in the DAT, ``(N disks)`` is
  always appended, so a name never depends on which other files are present.
  Names are compared case-insensitively (exFAT SD cards).
* Our own playlists that are no longer part of the plan and point at missing
  files, or duplicate a planned playlist, are reported as ``stale`` and removed
  by :func:`write_m3us`.
"""

from __future__ import annotations

import os
import re
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, Collection, Iterable, Mapping, Optional, Sequence

from . import tags as _tags
from .organiser import TEMP_MARKER, safe_filename

if TYPE_CHECKING:
    from .datfile import Rom
    from .scanner import Entry, Match, ScanResult

M3U_MARKER = "# Generated by simple-rom-organiser"
PUAE_MAX_DISKS = 20
ARCHIVE_EXTS = {".zip", ".7z"}           # what PUAE can open inside an m3u
UNSUPPORTED_ARCHIVE_EXTS = {".rar"}

_DISK_TOKEN = re.compile(
    r"\((?:Disk|Side) ([0-9]+|[A-Z]) of ([0-9]+|[A-Z])\)((?:\([^()]*\))*)"
)
_PAREN = re.compile(r"\(([^()]*)\)")
_FLAG = re.compile(r"\[[^\[\]]*\]")


# --------------------------------------------------------------------------- parsing


def _to_number(token: str) -> int:
    return int(token) if token.isdigit() else ord(token) - ord("A") + 1


@dataclass(frozen=True)
class DiskName:
    """A TOSEC rom name split into its multi-disk parts."""

    title: str               # name minus disk token, labels and flags
    index: int
    total: int
    label: str               # media label(s) after the token, "" if none
    flags: tuple[str, ...]   # "[...]" groups in order


def parse_disk_name(name: str) -> Optional[DiskName]:
    """Parse ``name`` (with or without extension); None if it has no disk token."""
    stem = name
    dot = stem.rfind(".")
    if dot > 0 and " " not in stem[dot:] and len(stem) - dot <= 5:
        stem = stem[:dot]
    m = _DISK_TOKEN.search(stem)
    if not m:
        return None
    index, total = _to_number(m.group(1)), _to_number(m.group(2))
    if total < 2 or index < 1:
        return None
    label = " - ".join(p.strip() for p in _PAREN.findall(m.group(3)) if p.strip())
    rest = stem[m.end():]
    flags = tuple(_FLAG.findall(rest))
    title = (stem[: m.start()].rstrip() + _FLAG.sub("", rest)).strip()
    return DiskName(title=title, index=index, total=total, label=label, flags=flags)


# --------------------------------------------------------------------------- grouping


@dataclass
class DiskSet:
    key: str
    total: int
    disks: dict[int, "Match"]
    missing: list[int]
    directory: Path
    labels: dict[int, str] = field(default_factory=dict)
    roms: dict[int, "Rom"] = field(default_factory=dict)
    flags: tuple[str, ...] = ()
    dat: str = ""  # sets never span DATs
    note: str = ""  # why the set is what it is (informational)
    base: str = ""  # title + dump flags (used to detect names shared by several totals)
    full_key: str = ""  # title + every flag of the anchor (fallback name on a collision)

    @property
    def complete(self) -> bool:
        return not self.missing and len(self.disks) == self.total


@dataclass(frozen=True)
class DiskCand:
    """One local disk that may fill a slot. ``ref`` is the caller's handle (opaque to us)."""

    ref: Any
    name: str  # TOSEC rom name (with or without extension)


@dataclass
class SlotSet:
    """One playlist-to-be: for every disk slot the newest compatible disk the user has."""

    identity: tuple
    total: int
    anchor: Optional[DiskCand]      # the disk 1 the set is built around (None: no disk 1 at all)
    slots: dict[int, DiskCand]
    missing: list[int]
    flags: tuple[str, ...]
    labels: dict[int, str]
    name: str
    note: str = ""
    title: str = ""                 # anchor title (name minus disk token, labels and flags)

    @property
    def complete(self) -> bool:
        return not self.missing and len(self.slots) == self.total


def _abs(path: Path, root: Path) -> Path:
    return path if path.is_absolute() else root / path


def _usable(entry: "Entry") -> bool:
    if entry.member is None:
        return True
    ext = entry.path.suffix.lower()
    return ext in ARCHIVE_EXTS and ext not in UNSUPPORTED_ARCHIVE_EXTS


# Standard TOSEC dump-flag codes ([cr], [t +2], [a2], [b dump] ...). Any other
# bracketed note ([!], [bootable], [cp manual code], [docs], [HD], [1Mb Chip] ...)
# describes one disk and does not make it incompatible with the rest of a set,
# except notes that mark a different build ([beta 3], [AGA version] ...).
_DUMP_FLAG = re.compile(r"^\[(?:cr|f|h|m|p|t|tr|o|u|v|b|a)\d*(?:[ \]])")
_BUILD_NOTE = re.compile(r"^\[(?:beta|alpha|proto(?:type)?|preview|pre-release|demo|compilation)\b|version\]$",
                         re.IGNORECASE)
_BARE_CODE = re.compile(r"^([a-z]+)\d*$")
_CODE_WITH_TEXT = re.compile(r"^([a-z]+)\d* ")


def is_neutral_flag(flag: str) -> bool:
    """True for informational flags that don't distinguish dump variants."""
    return not _DUMP_FLAG.match(flag) and not _BUILD_NOTE.search(flag)


def generalises(flag: str, other: str) -> bool:
    """True when dump flag ``flag`` is a bare/shorter form of ``other`` (same code).

    ``[cr]`` / ``[cr2]`` generalise ``[cr CSL]``; ``[cr Galahad]`` generalises
    ``[cr Galahad v1]``; ``[h PDX]`` generalises ``[h PDX - RSi]``. ``[a]`` does not
    generalise ``[a2]`` (different alternates).
    """
    c, v = flag[1:-1], other[1:-1]
    if c == v:
        return False
    if v.startswith(c + " "):
        return True
    bare = _BARE_CODE.match(c)
    if bare:
        code = _CODE_WITH_TEXT.match(v)
        return code is not None and code.group(1) == bare.group(1)
    return False


def _compat(flags: Iterable[str], variant: frozenset[str]) -> Optional[tuple[int, int, int]]:
    """(generalised, -shared, extra neutral) if a disk with ``flags`` fits ``variant``, else None."""
    fs = frozenset(flags)
    general = neutral = 0
    for f in fs - variant:
        if is_neutral_flag(f):
            neutral += 1
        elif any(generalises(f, v) for v in variant):
            general += 1
        else:
            return None
    return general, -len(fs & variant), neutral


def _dump_flags(flags: Iterable[str]) -> tuple[str, ...]:
    return tuple(f for f in flags if not is_neutral_flag(f))


# --- helpers that prefer tags.py's public API (amendment 6) and degrade gracefully

_DATE_PAREN = re.compile(r"\((?:[0-9x?]{4})(?:-[0-9x?]{2}(?:-[0-9x?]{2})?)?\)", re.IGNORECASE)


def _date_key(date: str) -> str:
    fn = getattr(_tags, "date_key", None)
    return fn(date) if fn else (date or "").replace("x", "0").replace("X", "0").replace("?", "0")


def _version_keys(names: list[str]) -> dict[str, tuple]:
    fn = getattr(_tags, "group_version_keys", None)
    if fn is not None:
        return fn(names, _tags.STYLE_TOSEC)
    return _tags._group_keys(names, _tags.STYLE_TOSEC)


def identity_of(name: str) -> tuple:
    """Game identity of a TOSEC rom name: same product regardless of version, date, disk, flags."""
    d = parse_disk_name(name)
    if d is not None:  # drop the disk token + labels so none of it is mistaken for a publisher
        name = d.title + "".join(d.flags)
    t = _tags.parse_name(name, _tags.STYLE_TOSEC)
    fn = getattr(_tags, "identity_key", None)
    if fn is not None:
        return fn(t)
    title = d.title if d else name
    if t.version:
        title = title.replace(t.version, "", 1)
    title = _DATE_PAREN.sub("", title)
    return (t.style, re.sub(r"\s+", " ", title).strip().casefold(), t.regions,
            () if t.languages_implied else t.languages)


_FALLBACK_RULES = {
    "bad_dump": re.compile(r"^b\d*(\s.*)?$"), "virus": re.compile(r"^v\d*(\s.*)?$"),
    "bad_size": re.compile(r"^[ou]\d*(\s.*)?$"), "modified": re.compile(r"^m\d*(\s.*)?$|^modified\b"),
    "faked": re.compile(r"^fake(d)?\b"), "unreleased": re.compile(r"^unreleased\b"),
}
_FALLBACK_PAREN = {"beta": "pre_release", "alpha": "pre_release", "preview": "pre_release",
                   "pre-release": "pre_release", "proto": "prototype", "unreleased": "unreleased",
                   "demo": "demo"}


def excluded_rules(name: str) -> frozenset[str]:
    """Exclusion rules (``tags.RULES`` keys) a rom name falls under."""
    t = _tags.parse_name(name, _tags.STYLE_TOSEC)
    fn = getattr(_tags, "exclusion_rules", None)
    if fn is not None:
        return fn(t)
    out: set[str] = set()
    for f in t.dump_flags:
        body = f[1:-1]
        for rule, rx in _FALLBACK_RULES.items():
            if rx.match(body):
                out.add(rule)
    for p in ([t.status] if t.status else []) + [x[1:-1] for x in t.flags if x.startswith("(")]:
        word = re.sub(r"\s+\d+$", "", p.casefold())
        if word.startswith("demo"):
            out.add("demo")
        elif word in _FALLBACK_PAREN:
            out.add(_FALLBACK_PAREN[word])
    return frozenset(out)


def _all_rules() -> frozenset[str]:
    return frozenset(getattr(_tags, "RULES", ("bad_dump", "virus", "bad_size", "pre_release", "prototype",
                                               "demo", "faked", "unreleased", "modified")))


# --------------------------------------------------------------------------- slot resolution


@dataclass
class _P:
    idx: int
    cand: DiskCand
    disk: DiskName
    vkey: tuple
    date: str


def _newest_first(p: _P) -> tuple:
    return (p.vkey, p.date)


def _pick_slot(options: list[_P], fset: frozenset[str], limit: Optional[tuple] = None) -> Optional[_P]:
    """Newest compatible disk for the slot (not newer than ``limit``); ties broken by exact
    flags, shared flags, then name."""
    ranked: list[tuple[tuple, _P]] = []
    for p in options:
        if limit is not None and p.vkey > limit:
            continue
        rank = _compat(p.disk.flags, fset)
        if rank is None:
            continue
        verified = 0 if "[!]" in p.disk.flags else 1      # a verified good dump wins a tie
        ranked.append(((rank[0], verified, *rank[1:], len(p.cand.name), p.cand.name, p.idx), p))
    ranked.sort(key=lambda kp: kp[0])
    best: Optional[_P] = None
    for _, p in ranked:
        if best is None or _newest_first(p) > _newest_first(best):
            best = p
    return best


def pick_borrowed(options: Sequence[DiskCand], anchor_flags: Iterable[str], vkeys: Mapping[str, tuple],
                  tier: Optional[Any] = None) -> Optional[DiskCand]:
    """The disk of ANOTHER edition that fills a slot (``borrow_other_editions``, Amendment 12).

    ``options`` = disks (all of the same slot number and disk total) the caller found eligible: same title,
    publisher and total, no quality exclusion, compatible chipset. The disk must still fit the anchor's dump
    flags (:func:`_compat`: a different crack, ``[t ..]``, ``[h ..]`` never fits; a bare disk fits any
    ``[cr X]``). ``tier(cand)`` ranks candidate groups, lowest first (same edition / selected language /
    any other); within a tier the newest ``(version, date)`` wins, ties by the crack-compatibility order of
    :func:`_pick_slot` (``vkeys`` only ranks - a borrowed disk may be newer than the anchor)."""
    fset = frozenset(anchor_flags)
    ps: list[_P] = []
    for i, c in enumerate(options):
        d = parse_disk_name(c.name)
        if d is None:
            continue
        date = _date_key(_tags.parse_name(c.name, _tags.STYLE_TOSEC).date)
        ps.append(_P(i, c, d, vkeys.get(c.name, (0,)), date))
    ranks = sorted({(tier(p.cand) if tier else 0) for p in ps})
    for r in ranks:
        best = _pick_slot([p for p in ps if (tier(p.cand) if tier else 0) == r], fset, None)
        if best is not None:
            return best.cand
    return None


def _slot_name(title: str, flags: tuple[str, ...], chosen: Collection[DiskName]) -> str:
    shared = [f for f in flags if not is_neutral_flag(f) or all(f in d.flags for d in chosen)]
    return title + "".join(shared)


def resolve_slots(cands: Sequence[DiskCand], vkeys: Optional[Mapping[str, tuple]] = None) -> list[SlotSet]:
    """Slot-wise multi-disk sets for the candidates of ONE game identity.

    Disks never mix across languages or chipsets (``tags.partition_key``: explicit language tags and
    ``AGA`` / ``OCS-AGA`` ... tags, which are no longer part of the identity): each partition is
    resolved on its own and the sets are merged.
    """
    parts: dict[tuple, list[DiskCand]] = {}
    for c in cands:
        parts.setdefault(_tags.partition_key(_tags.parse_name(c.name, _tags.STYLE_TOSEC)), []).append(c)
    if len(parts) <= 1:
        return _resolve_partition(cands, vkeys)
    out: list[SlotSet] = []
    for key in sorted(parts, key=repr):
        out.extend(_resolve_partition(parts[key], vkeys))
    out.sort(key=lambda s: (s.total, s.name.casefold(), s.name))
    return out


def _resolve_partition(cands: Sequence[DiskCand], vkeys: Optional[Mapping[str, tuple]] = None) -> list[SlotSet]:
    """:func:`resolve_slots` for candidates of one language / chipset partition.

    TOSEC only lists the disks that changed between versions, so ``X v1.1 (Disk 1 of 3)[cr SR]``
    goes with ``X (1990) (Disk 2 of 3)``: for every anchor (a disk 1) each slot takes the newest
    compatible disk that is not newer than the anchor. Callers pass only eligible disks
    (no excluded / bad variants). Incomplete sets are returned too (``missing`` lists the slots).
    """
    parsed: list[_P] = []
    names = [c.name for c in cands]
    keys = dict(vkeys) if vkeys is not None else _version_keys(names)
    for i, c in enumerate(cands):
        d = parse_disk_name(c.name)
        if d is None:
            continue
        if c.name not in keys:
            keys.update(_version_keys(names))
        date = _date_key(_tags.parse_name(c.name, _tags.STYLE_TOSEC).date)
        parsed.append(_P(i, c, d, keys.get(c.name, (0,)), date))

    by_total: dict[int, dict[int, list[_P]]] = {}
    for p in parsed:
        by_total.setdefault(p.disk.total, {}).setdefault(p.disk.index, []).append(p)

    built: list[tuple[frozenset, SlotSet, Optional[_P]]] = []
    for total in sorted(by_total):
        by_index = by_total[total]
        anchors = sorted(by_index.get(1, []), key=lambda p: (p.cand.name, p.idx))
        # (disk 1 or None, flag set the other slots must fit)
        plans: list[tuple[Optional[_P], frozenset[str], _P]] = [(a, frozenset(a.disk.flags), a) for a in anchors]
        pool = sorted((p for ps in by_index.values() for p in ps), key=lambda p: (p.cand.name, p.idx))
        if not anchors:
            newest = max(pool, key=lambda p: (_newest_first(p), -len(p.cand.name), p.cand.name))
            plans.append((None, frozenset(newest.disk.flags), newest))
        else:
            # Flag sets only some other disk carries (a trainer on disk 2 only): disk 1 is then
            # the newest one compatible with that flag set.
            known = {f for _, f, _ in plans}
            for p in pool:
                f = frozenset(p.disk.flags)
                if f in known:
                    continue
                known.add(f)
                d1 = _pick_slot(by_index[1], f)
                if d1 is not None:
                    plans.append((d1, f, p))
        for real, fset, ref in plans:
            chosen: dict[int, _P] = {}
            if real is not None:
                chosen[1] = real
            else:
                chosen[ref.disk.index] = ref
            for i in range(1, total + 1):
                if i not in chosen:
                    p = _pick_slot(by_index.get(i, []), fset, (real or ref).vkey)
                    if p is not None:
                        chosen[i] = p
            sel = frozenset((i, p.idx) for i, p in chosen.items())
            head = real or ref
            flags = ref.disk.flags
            ss = SlotSet(
                identity=(), total=total, anchor=real.cand if real else None,
                slots={i: p.cand for i, p in sorted(chosen.items())},
                missing=[i for i in range(1, total + 1) if i not in chosen],
                flags=flags, labels={i: p.disk.label for i, p in sorted(chosen.items())},
                name=_slot_name(head.disk.title, flags, [p.disk for p in chosen.values()]),
                note="" if real else "no disk 1 in the set", title=head.disk.title,
            )
            built.append((sel, ss, real))

    out: list[SlotSet] = []
    seen: set[frozenset] = set()
    for sel, ss, _ in built:
        if sel in seen:
            continue
        seen.add(sel)
        if not ss.complete and any(o != sel and sel < o for o, _, _ in built):
            continue
        out.append(ss)
    out.sort(key=lambda s: (s.total, s.name.casefold(), s.name))
    return out


@dataclass
class _Local:
    match: "Match"
    rom: "Rom"
    ident: tuple[str, str]


def group_disk_sets(result: "ScanResult", dats: Optional[Collection[str]] = None,
                    exclude_rules: Optional[Collection[str]] = None) -> list[DiskSet]:
    """All multi-disk sets (total >= 2) found among the matched files, sorted by key.

    ``dats`` restricts grouping to those DAT names (e.g. ``platform.m3u_dats``);
    None means every DAT. Sets are grouped per (DAT, game identity) and never span DATs.
    ``exclude_rules`` (default: all ``tags.RULES``) are the exclusion rules whose roms are
    never part of a set (bad dumps, pre-releases, ...).
    """
    rules = _all_rules() if exclude_rules is None else frozenset(exclude_rules)
    groups: dict[tuple[str, tuple], list[DiskCand]] = {}
    seen: set[tuple] = set()
    for m in result.matched:
        e = m.entry
        if not _usable(e):
            continue
        ident = (str(_abs(e.path, result.root)), e.member or "")
        for rom in m.primary:
            if dats is not None and rom.dat not in dats:
                continue
            if parse_disk_name(rom.name) is None:
                continue
            k = (ident, rom.dat, rom.name)
            if k in seen:
                continue
            seen.add(k)
            if rules and excluded_rules(rom.name) & rules:
                continue
            groups.setdefault((rom.dat, identity_of(rom.name)), []).append(
                DiskCand(_Local(m, rom, ident), rom.name))

    sets: list[DiskSet] = []
    for (dat, identity), cands in groups.items():
        found = resolve_slots(cands)
        for ss in found:
            # Incomplete variants of a game that has a complete set (same disk count) are noise.
            if not ss.complete and any(o.complete and o.total == ss.total for o in found):
                continue
            slots = {i: c.ref for i, c in ss.slots.items()}
            first = slots[min(slots)]
            sets.append(DiskSet(
                key=ss.name, total=ss.total,
                disks={i: r.match for i, r in slots.items()},
                missing=list(ss.missing),
                directory=_abs(first.match.entry.path, result.root).parent,
                labels=dict(ss.labels), roms={i: r.rom for i, r in slots.items()},
                flags=ss.flags, dat=dat, note=ss.note,
                base=ss.title + "".join(_dump_flags(ss.flags)),
                full_key=ss.title + "".join(ss.flags),
            ))
    sets.sort(key=lambda s: (s.key.lower(), s.total, s.dat))
    return sets


# --------------------------------------------------------------------------- m3u files


@dataclass
class M3UOp:
    path: Path
    lines: list[str]
    status: str  # write | ok | conflict | incomplete | stale
    reason: str = ""
    dat: str = ""
    notes: list[str] = field(default_factory=list)    # "disk 2 borrowed from the (DE) edition (...)" per borrowed disk


def _fold(p: Path) -> str:
    return os.path.normcase(str(p)).casefold()


def find_m3us(root: Path) -> list[Path]:
    """Every ``*.m3u`` under root (hidden files/dirs and symlinked dirs skipped), sorted."""
    out: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for f in filenames:
            if f.lower().endswith(".m3u") and not f.startswith("."):
                out.append(Path(dirpath) / f)
    out.sort(key=lambda p: str(p).casefold())
    return out


def _read_text(path: Path) -> str:
    with open(path, encoding="utf-8-sig", errors="surrogateescape", newline="") as f:
        return f.read(1 << 20)  # playlists are tiny; never read a huge mislabelled file


def entry_paths(lines: Iterable[str], directory: Path) -> list[Path]:
    """Disk paths referenced by m3u ``lines`` (labels and ``#member`` selectors removed)."""
    out: list[Path] = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        path = line.split("|", 1)[0].strip()
        hash_at = path.find("#", 1)
        while hash_at > 0:  # archive.zip#member.adf -> archive.zip
            head = path[:hash_at]
            if os.path.splitext(head)[1].lower() in ARCHIVE_EXTS | UNSUPPORTED_ARCHIVE_EXTS:
                path = head
                break
            hash_at = path.find("#", hash_at + 1)
        if not path:
            continue
        p = Path(path)
        out.append(Path(os.path.normpath(p if p.is_absolute() else directory / p)))
    return out


def read_m3u(path: Path) -> Optional[tuple[bool, list[Path]]]:
    """(made by us?, referenced disk paths) for an m3u file, or None if unreadable."""
    try:
        text = _read_text(path)
    except OSError:
        return None
    lines = text.replace("\r\n", "\n").split("\n")
    return lines[:1] == [M3U_MARKER], entry_paths(lines, path.parent)


def read_own_m3u_text(path: Path) -> Optional[str]:
    """Full text of an m3u generated by this app, or None (not ours / unreadable)."""
    try:
        text = _read_text(path)
    except OSError:
        return None
    return text if text.replace("\r\n", "\n").split("\n")[:1] == [M3U_MARKER] else None


def _member_counts(result: "ScanResult") -> dict[str, int]:
    counts: dict[str, int] = {}
    for e in [m.entry for m in result.matched] + list(result.unmatched):
        if e.member is not None:
            p = str(_abs(e.path, result.root))
            counts[p] = counts.get(p, 0) + 1
    return counts


def _disk_line(entry: "Entry", directory: Path, root: Path, member_counts: dict[str, int]) -> str:
    path = _abs(entry.path, root)
    rel = os.path.relpath(path, directory).replace(os.sep, "/")
    if entry.member is not None and member_counts.get(str(path), 1) > 1:
        rel = f"{rel}#{entry.member}"
    if rel.startswith("#"):
        rel = "./" + rel
    return rel


def _content(lines: list[str]) -> str:
    return "\n".join(lines) + "\n"


def _existing_state(path: Path, lines: list[str]) -> tuple[str, str]:
    """(status, reason) of ``path`` relative to the content we would write."""
    if not path.exists():
        return "write", ""
    try:
        text = _read_text(path)
    except OSError as exc:
        return "conflict", f"cannot read existing m3u: {exc}"
    if text.replace("\r\n", "\n") == _content(lines):
        return "ok", "up to date"
    if text.splitlines()[:1] == [M3U_MARKER]:
        return "write", "updates m3u previously generated by simple-rom-organiser"
    return "conflict", "an m3u not created by simple-rom-organiser exists"


def _ambiguous_bases(result: "ScanResult") -> set[tuple[str, str]]:
    """(dat, title + dump flags) that stand for sets of different disk counts in the DAT."""
    totals: dict[tuple[str, str], set[int]] = {}
    seen: set[tuple[str, str]] = set()
    for rom in list(result.missing) + [r for m in result.matched for r in m.roms]:
        k = (getattr(rom, "dat", ""), rom.name)
        if k in seen:
            continue
        seen.add(k)
        d = parse_disk_name(rom.name)
        if d is not None:
            totals.setdefault((k[0], d.title + "".join(_dump_flags(d.flags))), set()).add(d.total)
    return {k for k, v in totals.items() if len(v) > 1}


def plan_m3us(result: "ScanResult", savedisk: bool = False, labels: bool = True,
              dats: Optional[Collection[str]] = None,
              exclude_rules: Optional[Collection[str]] = None) -> list[M3UOp]:
    """Plan one m3u per multi-disk set (next to disk 1). Incomplete sets are reported, not written.

    ``dats``: only sets from these DATs (pass ``platform.m3u_dats``); None = all.
    ``exclude_rules``: exclusion rules (default all ``tags.RULES``) whose roms are never used.
    Our own playlists elsewhere under root that went stale are reported as ``stale``.
    """
    member_counts = _member_counts(result)
    sets = group_disk_sets(result, dats, exclude_rules)
    ambiguous = _ambiguous_bases(result)

    # Names: complete sets claim theirs first; incomplete sets never reserve one.
    used: set[str] = set()
    names: dict[int, Path] = {}
    for ds in sorted(sets, key=lambda s: not s.complete):
        suffix = f" ({ds.total} disks)" if (ds.dat, ds.base) in ambiguous else ""
        key = ds.key + suffix
        path = ds.directory / safe_filename(key + ".m3u")
        if _fold(path) in used and ds.full_key and ds.full_key != ds.key:
            # sets that differ only by a per-disk note: name them with all their flags
            path = ds.directory / safe_filename(ds.full_key + suffix + ".m3u")
        n = 2
        while _fold(path) in used:
            path = ds.directory / safe_filename(f"{key} ({n}).m3u")
            n += 1
        if ds.complete:
            used.add(_fold(path))
        names[id(ds)] = path

    ops: list[M3UOp] = []
    for ds in sets:
        path = names[id(ds)]
        if not ds.complete:
            reason = "missing disk " + ", ".join(str(i) for i in ds.missing)
            ops.append(M3UOp(path, [], "incomplete", f"{reason} ({ds.note})" if ds.note else reason, ds.dat))
            continue

        lines = [M3U_MARKER]
        bad: list[str] = []
        for i, match in ds.disks.items():
            line = _disk_line(match.entry, ds.directory, result.root, member_counts)
            if "|" in line or line != line.strip() or "\n" in line or "\r" in line:
                bad.append(line)
            if labels:
                label = (ds.labels.get(i) or f"Disk {i}").replace("\n", " ").strip()
                line = f"{line}|{label}"
            lines.append(line)
        if savedisk:
            lines.append("#SAVEDISK:")
        if bad:
            ops.append(M3UOp(path, lines, "conflict",
                             "filename can't be used in an m3u (contains '|' or edge spaces): "
                             + bad[0] + "; run organise first", ds.dat))
            continue
        status, reason = _existing_state(path, lines)
        extras = [reason, ds.note]
        if ds.total > PUAE_MAX_DISKS:
            extras.append(f"PUAE only loads the first {PUAE_MAX_DISKS} disks")
        ops.append(M3UOp(path, lines, status, ", ".join(x for x in extras if x), ds.dat))
    ops.extend(_stale_ops(result.root, ops))
    return ops


def _stale_ops(root: Path, ops: list[M3UOp], moving: Collection[str] = ()) -> list[M3UOp]:
    """Our playlists not in the plan that point at missing (or moving) files or duplicate a planned one."""
    moving_set = {_fold(Path(p)) for p in moving}
    planned = {_fold(op.path) for op in ops}
    planned_sets = {frozenset(_fold(p) for p in entry_paths(op.lines, op.path.parent)): op.path
                    for op in ops if op.status in ("write", "ok")}
    out: list[M3UOp] = []
    try:
        found = find_m3us(root)
    except OSError:
        return out
    for path in found:
        if _fold(path) in planned:
            continue
        info = read_m3u(path)
        if info is None or not info[0]:
            continue
        entries = info[1]
        missing = [e for e in entries if not os.path.lexists(e) or _fold(e) in moving_set]
        twin = planned_sets.get(frozenset(_fold(e) for e in entries))
        if missing:
            out.append(M3UOp(path, [], "stale", f"made by this app; {len(missing)} of its disks no longer "
                                                "exist at that place - it will be removed"))
        elif twin is not None and entries:
            out.append(M3UOp(path, [], "stale", f"made by this app; replaced by {twin.name} - it will be removed"))
    return out


def _write_new(path: Path, text: str) -> None:
    """Write via a unique temp file in the same folder, then replace ``path``."""
    tmp = path.with_name(f".{path.name}{TEMP_MARKER}{uuid.uuid4().hex[:8]}")
    try:
        with open(tmp, "x", encoding="utf-8", errors="surrogateescape", newline="\n") as f:
            f.write(text)
        os.replace(tmp, path)
    finally:
        if os.path.lexists(tmp):
            try:
                os.unlink(tmp)
            except OSError:
                pass


def write_m3us(ops: Iterable[M3UOp]) -> dict:
    """Write the ``write`` ops and remove the ``stale`` ones (re-checking ownership first).

    Returns ``{"written", "removed", "failed": [{"path", "error"}], "skipped"}``.
    """
    written = skipped = removed = 0
    failed: list[dict[str, str]] = []
    for op in ops:
        if op.status == "stale":
            info = read_m3u(op.path)
            if info is None or not info[0]:
                skipped += 1
                continue
            try:
                os.unlink(op.path)
                removed += 1
            except OSError as exc:
                failed.append({"path": str(op.path), "error": str(exc)})
            continue
        if op.status != "write":
            skipped += 1
            continue
        status, reason = _existing_state(op.path, op.lines)
        if status == "ok":
            skipped += 1
            continue
        if status != "write":
            failed.append({"path": str(op.path), "error": reason})
            continue
        try:
            _write_new(op.path, _content(op.lines))
            written += 1
        except (OSError, UnicodeError) as exc:
            failed.append({"path": str(op.path), "error": str(exc)})
    return {"written": written, "removed": removed, "failed": failed, "skipped": skipped}



# --------------------------------------------------------------------------- library playlists


@dataclass
class PlaylistDisk:
    slot: int
    path: Path               # FINAL location of the disk file
    member: Optional[str]    # archive member, if the disk lives inside a zip/7z
    label: str = ""


@dataclass
class PlaylistSpec:
    name: str                # file stem (no ".m3u")
    dat: str
    total: int
    disks: list[PlaylistDisk]
    notes: list[str] = field(default_factory=list)    # one line per disk borrowed from another edition


def content_of(lines: list[str]) -> str:
    return _content(lines)


def plan_playlists(specs: Iterable[PlaylistSpec], root: Path, savedisk: bool = False, labels: bool = True,
                   member_counts: Optional[Mapping[str, int]] = None) -> list[M3UOp]:
    """One playlist per spec, next to the lowest slot's disk. Status write | ok | conflict.

    Name collisions (case-insensitive, same folder) get `` (2)``, `` (3)`` ... in spec order.
    """
    counts = member_counts or {}
    used: set[str] = set()
    ops: list[M3UOp] = []
    for spec in specs:
        disks = sorted(spec.disks, key=lambda d: d.slot)
        if not disks:
            continue
        directory = _abs(disks[0].path, root).parent
        path = directory / safe_filename(spec.name + ".m3u")
        n = 2
        while _fold(path) in used:
            path = directory / safe_filename(f"{spec.name} ({n}).m3u")
            n += 1
        used.add(_fold(path))
        lines = [M3U_MARKER]
        bad: list[str] = []
        for d in disks:
            full = _abs(d.path, root)
            rel = os.path.relpath(full, directory).replace(os.sep, "/")
            if d.member is not None and counts.get(str(full), 1) > 1:
                rel = f"{rel}#{d.member}"
            if rel.startswith("#"):
                rel = "./" + rel
            if "|" in rel or rel != rel.strip() or "\n" in rel or "\r" in rel:
                bad.append(rel)
            if d.member is not None and os.path.splitext(str(full))[1].lower() not in ARCHIVE_EXTS:
                bad.append(rel)
            line = rel
            if labels:
                line = f"{rel}|{(d.label or f'Disk {d.slot}').replace(chr(10), ' ').strip()}"
            lines.append(line)
        if savedisk:
            lines.append("#SAVEDISK:")
        if bad:
            ops.append(M3UOp(path, lines, "conflict",
                             "filename can't be used in an m3u (contains '|', edge spaces or an "
                             "unsupported archive): " + bad[0], spec.dat))
            continue
        status, reason = _existing_state(path, lines)
        extras = [reason]
        if spec.total > PUAE_MAX_DISKS:
            extras.append(f"PUAE only loads the first {PUAE_MAX_DISKS} disks")
        ops.append(M3UOp(path, lines, status, ", ".join(x for x in extras if x), spec.dat, list(spec.notes)))
    return ops


def plan_stale(root: Path, planned: list[M3UOp], moving: Collection[str] = ()) -> list[M3UOp]:
    """Our own playlists not in ``planned`` whose disks are gone, about to move (``moving`` =
    absolute disk paths) or that a planned playlist replaces; status ``stale``."""
    return _stale_ops(root, planned, moving)


def write_playlist(path: Path, text: str, replace_own: bool = False) -> tuple[str, int]:
    """Write a playlist atomically; returns (sha1, size). Raises FileExistsError unless the
    target is absent or (``replace_own``) one of our own playlists."""
    import hashlib
    data = text.encode("utf-8", errors="surrogateescape")
    if os.path.lexists(path):
        if not replace_own or read_own_m3u_text(path) is None:
            raise FileExistsError(str(path))
    tmp = path.with_name(f".{path.name}{TEMP_MARKER}{uuid.uuid4().hex[:8]}")
    try:
        with open(tmp, "xb") as f:
            f.write(data)
        if replace_own:
            os.replace(tmp, path)
        else:
            try:
                os.link(tmp, path)  # fails with FileExistsError instead of overwriting
            except FileExistsError:
                raise
            except (OSError, NotImplementedError, AttributeError):
                # FAT/exFAT have no hard links: check-then-rename.
                if os.path.lexists(path):
                    raise FileExistsError(str(path)) from None
                os.rename(tmp, path)
    finally:
        if os.path.lexists(tmp):
            try:
                os.unlink(tmp)
            except OSError:
                pass
    return hashlib.sha1(data).hexdigest(), len(data)
