"""Plan, apply and undo moves that organise a platform folder into DAT folders.

Target layout ``per_dat`` (see docs/ARCHITECTURE.md, Amendment 1; TOSEC platforms)::

    <root>/
      <DAT name>/            one flat folder per DAT (safe_filename(dat name), no version)
      _unmatched/            everything that matched nothing, relative paths preserved

Layout ``flat`` (Amendment 4; No-Intro consoles): matched files live directly in
``<root>/``; ``_unmatched/`` as above. Both layouts may also use the reason folders, all
direct children of ``<root>`` (Amendment 9; see :mod:`folders`, the only list of the names):
``_duplicates/`` (spare copies of one rom), ``_excluded/`` (bad dumps, betas,
demos ... - library profile), ``_superseded/`` (older versions), ``_incomplete/`` (multi-disk
sets with a missing disk), each holding ``<path relative to root>``, and
``_converted_originals/`` (originals kept by "Convert to No-Intro format"; always left where
they are). A file under a reason folder that no longer qualifies for it moves back to its
canonical place (Amendment 6). Files of the legacy layout (``_unmatched/_excluded/...`` etc.)
are recognised as being in that reason folder and move to the top-level one.

Rules:

* Matched loose file -> ``<canonical dir>/<rom.name>``; matched archive with a
  single member -> ``<canonical dir>/<archive stem><ext>`` (the member inside is
  never rewritten; the stem is the No-Intro set name or the TOSEC game name). Files
  matched via an alternate hash (copier header, byte-swapped N64) keep an honest
  extension (``.smc``, ``.v64``, ``.n64``, ``.nes``) - organising never converts content. The DAT is the primary (highest priority) match's DAT. The DAT
  folder is canonical: matched files anywhere under root (incl. ``_unmatched/``)
  are moved there.
* Multi-member archives: moved to the DAT folder only if every member matched and
  they share one game; skipped if only some members match; unmatched otherwise.
* Unmatched files, unsupported archives -> ``<root>/_unmatched/<path relative to
  root>``; files already under ``_unmatched/`` stay where they are. Exceptions
  (status ``skip``): files inside the folder of a DAT that is not loaded, known
  frontend/emulator files (``gamelist.xml``, ``rom.key``, ``*.uae`` ...), symbolic
  links.
* A file whose hash matches several roms (TOSEC duplicates) keeps its name if it
  already equals one of them, else the closest name (``difflib``) wins; ties ->
  alphabetical first.
* Targets go through :func:`safe_filename` (Windows / FAT / exFAT safe names).
* Several local files that are the same rom (same content, same DAT rom, loose or archived):
  one is kept (already canonical, else outside the reserved folders, exact content, loose,
  shortest path, alphabetical) and the others move to ``_duplicates/``.
* Nothing is ever overwritten: moves use ``link`` + ``unlink`` where the
  filesystem supports hard links (atomic no-overwrite), else check-then-rename.
  Duplicates (identical content already at the target) are left in place and
  reported, unless they block another file's canonical name (then they go to
  ``_unmatched/``). Target claims are compared case-insensitively (exFAT SD cards);
  case-only renames and swap cycles go through a temporary name.
* Playlists generated by this app (first line ``# Generated by simple-rom-organiser``)
  that reference files being moved are deleted (status ``delete``; their content
  is kept in the undo log) - write the M3Us again afterwards. User playlists are
  never touched but reported (``skip``) when their disks move.
* After applying, directories that became empty because of our moves are removed
  (never root, DAT folders, ``_unmatched`` or pre-existing empty dirs; emptied reason folders go).
* Every apply journals into ``<root>/.romorg-undo-<timestamp>.json`` *before* each
  step (JSON lines, paths relative to root), so an interrupted apply can still be
  undone. :func:`undo` restores the original paths, refuses anything outside the
  log's folder, and keeps the entries it could not restore for a later retry.
"""

from __future__ import annotations

import copy
import dataclasses
import difflib
import errno
import functools
import filecmp
import hashlib
import json
import os
import re
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path, PurePosixPath
from typing import IO, TYPE_CHECKING, Any, Callable, Iterable, Optional, Sequence

if TYPE_CHECKING:
    from . import library, m3u
    from .datfile import Rom
    from .scanner import Entry, Match, ScanResult

UNDO_PREFIX = ".romorg-undo-"
UNDONE_SUFFIX = ".undone"
from . import folders  # noqa: E402  (the reserved folder names live in folders.py only)
from .folders import (CODE_DIRS, CONVERTED_DIR, DUPLICATES_DIR, EXCLUDED_DIR, INCOMPLETE_DIR,  # noqa: E402,F401
                      REASON_DIRS, RESERVED_DIRS, SUPERSEDED_DIR, UNMATCHED_DIR)

TEMP_MARKER = ".romorg-tmp-"
CONVERT_TEMP_MARKER = ".romorg-convert-"  # clean files being written by convert.py ("tmp" records)
LOG_VERSION = 3
MAX_NAME_BYTES = 255
FSYNC_EVERY = 32  # journal records between fsyncs (each record is flushed immediately)

MOVE_STATUSES = ("move", "rename")  # "rename" accepted for backwards compatibility
DELETE_STATUS = "delete"            # our own stale m3u playlists
ACTION_STATUSES = MOVE_STATUSES + (DELETE_STATUS,)

# Unmatched files that belong next to the ROMs (frontends / emulators) stay in place.
KEEP_NAMES = {"systeminfo.txt", "metadata.txt", "metadata.pegasus.txt", "gamelist.xml",
              "rom.key", "desktop.ini", "thumbs.db"}
KEEP_SUFFIXES = {".uae", ".key", ".srm", ".sav", ".state", ".nvram"}
# Frontend media folders inside a flat console root (EmulationStation, Pegasus ...).
KEEP_DIRS = {"media", "images", "videos", "manuals", "downloaded_images", "snap", "boxart"}

LAYOUT_PER_DAT = "per_dat"  # one folder per DAT (same values as platforms.LAYOUT_*)
LAYOUT_FLAT = "flat"        # everything directly in the root

# A file matched with its header skipped that claims to be clean gets the headered extension.
HEADERED_EXT = {".sfc": ".smc", ".unh": ".nes"}
BYTE_ORDER_EXT = {"v64": ".v64", "n64": ".n64"}

ProgressFn = Callable[[int, int, str], None]

_ILLEGAL_CHARS = set(':?*"<>|\\/')
_ILLEGAL_RE = re.compile(r'[:?*"<>|\\/\x00-\x1f\x7f]')
_WINDOWS_RESERVED = {
    "CON", "PRN", "AUX", "NUL",
    *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}


@dataclass
class RenameOp:
    src: Path
    dst: Path
    status: str  # move | ok | conflict | duplicate | skip | delete
    reason: str = ""
    rom_name: str = ""
    kind: str = "move"      # "rename" (same directory) | "move" (different directory) | "m3u"
    dat: str = ""           # target DAT name; "" for unmatched files
    unmatched: bool = False  # True when the target is a reserved app folder (_unmatched/, _excluded/ ...)
    superseded_by: str = ""  # latest_only: name of the newer rom that supersedes this one
    code: str = ""           # "" | "excluded" | "superseded" | "incomplete" | "duplicate" (reason folder)
    keeper: str = ""         # duplicates: path (relative to root) of the file that is kept
    missing: tuple[int, ...] = ()  # incomplete: disk numbers the set lacks
    flags_text: str = ""     # excluded: the exact flags that caused it, e.g. "[b corrupt file]"
    folder: str = ""         # the reserved top-level folder the target is in ("_unmatched", "_excluded" ... or "")
    reasons: tuple[str, ...] = ()  # excluded: every reason code (rules, "flag_<x>", "language"), first = primary


# --------------------------------------------------------------------------- names


def _split_ext(name: str) -> tuple[str, str]:
    """Split off the last extension (``"a.b.adf"`` -> ``("a.b", ".adf")``)."""
    dot = name.rfind(".")
    if dot <= 0 or dot == len(name) - 1:
        return name, ""
    return name[:dot], name[dot:]


def _truncate_utf8(text: str, max_bytes: int) -> str:
    encoded = text.encode("utf-8", "surrogateescape")
    if len(encoded) <= max_bytes:
        return text
    return encoded[:max_bytes].decode("utf-8", errors="ignore")


@functools.lru_cache(maxsize=131072)
def safe_filename(name: str) -> str:
    """Return ``name`` made safe for Windows/FAT/exFAT and common Linux filesystems.

    Replaces ``: ? * " < > | \\ /`` and control characters with ``_``, strips
    trailing dots/spaces, guards Windows reserved device names and keeps the
    result within 255 UTF-8 bytes while preserving the extension.
    """
    out = _ILLEGAL_RE.sub("_", name).rstrip(" .")
    if not out:
        return "_"
    stem, ext = _split_ext(out)
    if stem.split(".")[0].upper() in _WINDOWS_RESERVED:
        stem = "_" + stem
    if len((stem + ext).encode("utf-8", "surrogateescape")) > MAX_NAME_BYTES:
        ext_bytes = len(ext.encode("utf-8", "surrogateescape"))
        if ext_bytes >= MAX_NAME_BYTES // 2:  # absurd extension: just cut the whole thing
            stem, ext = stem + ext, ""
            ext_bytes = 0
        stem = _truncate_utf8(stem, MAX_NAME_BYTES - ext_bytes).rstrip(" .") or "_"
    return stem + ext


def dat_folder_name(dat_name: str) -> str:
    """Folder name for a DAT: the DAT name (no version), sanitised."""
    return safe_filename(dat_name)


def canonical_dir(root: Path, dat_name: str, layout: Optional[str] = LAYOUT_PER_DAT) -> Path:
    """Folder matched files of ``dat_name`` belong in: ``root/<DAT folder>`` or ``root`` (flat)."""
    return _canonical_dir_cached(os.fspath(root), dat_name, layout)


@functools.lru_cache(maxsize=4096)
def _canonical_dir_cached(root: str, dat_name: str, layout: Optional[str]) -> Path:
    base = Path(root)           # Paths are immutable: every file of a DAT shares this one
    return base if layout == LAYOUT_FLAT else base / dat_folder_name(dat_name)


def _archive_stem(rom: "Rom") -> str:
    """Archive target stem: the No-Intro set name, else the (TOSEC) game name."""
    return getattr(rom, "set_name", "") or rom.game


def _rom_stem(rom: "Rom") -> str:
    return getattr(rom, "set_name", "") or _split_ext(rom.name)[0]


def _target_name(rom: "Rom", src_name: str, archive_ext: Optional[str] = None,
                 matched_via: str = "raw", byte_order: str = "") -> str:
    """:func:`target_filename` before sanitising."""
    if archive_ext is not None:
        return _archive_stem(rom) + archive_ext
    if matched_via in ("", "raw"):
        return rom.name
    stem = _rom_stem(rom)
    _, rom_ext = _split_ext(rom.name)
    _, src_ext = _split_ext(src_name)
    if matched_via == "byteswapped":
        ext = BYTE_ORDER_EXT.get(byte_order) or src_ext or rom_ext
    elif not src_ext or src_ext.casefold() == rom_ext.casefold():
        # Claims to be clean (or has no extension): the headered variant of the rom's ext.
        ext = HEADERED_EXT.get(rom_ext.casefold(), rom_ext)
    else:
        ext = src_ext
    return stem + ext


def target_filename(rom: "Rom", src_name: str, archive_ext: Optional[str] = None,
                    matched_via: str = "raw", byte_order: str = "") -> str:
    """Canonical filename for a file matching ``rom`` (always :func:`safe_filename`-ed).

    Archive -> ``<archive stem><archive_ext>``; raw match -> ``rom.name``;
    byte-swapped N64 -> ``<stem>.v64`` / ``<stem>.n64`` (by ``byte_order``);
    headerless -> ``<stem><original ext>``, except when the original extension is the
    rom's own (it claims to be clean) or missing -> the headered one (``.sfc`` -> ``.smc``,
    ``.unh`` -> ``.nes``; other extensions unchanged). ``stem`` = the set name, else the
    rom name without its extension. Content is never converted, so the extension stays honest.
    """
    return safe_filename(_target_name(rom, src_name, archive_ext, matched_via, byte_order))


def choose_rom(current: str, roms: Sequence["Rom"], key: Callable[["Rom"], str]) -> tuple["Rom", list["Rom"]]:
    """Pick the rom whose ``key`` best matches ``current``; return (chosen, alternatives).

    Exact (or exact-after-sanitising) name wins, else highest difflib ratio,
    ties broken alphabetically.
    """
    if len(roms) == 1:
        return roms[0], []
    ordered = sorted(roms, key=lambda r: (key(r), r.name))
    chosen: Optional["Rom"] = None
    for r in ordered:
        if key(r) == current or safe_filename(key(r)) == current:
            chosen = r
            break
    if chosen is None:
        best = -1.0
        for r in ordered:
            ratio = difflib.SequenceMatcher(None, current, key(r)).ratio()
            if ratio > best:
                best, chosen = ratio, r
    assert chosen is not None
    return chosen, [r for r in ordered if r is not chosen]


# --------------------------------------------------------------------------- fs helpers
# Small wrappers so tests can simulate a case-insensitive filesystem.


def _exists(p: Path) -> bool:
    return os.path.lexists(p)


def _same_file(a: Path, b: Path) -> bool:
    try:
        return os.path.samefile(a, b)
    except OSError:
        return False


def _same_content(a: Path, b: Path) -> bool:
    try:
        return filecmp.cmp(a, b, shallow=False)
    except OSError:
        return False


def _fold(p: Path) -> str:
    """Case-insensitive key for a path (exFAT/FAT/NTFS/APFS compare names this way)."""
    return os.path.normcase(str(p)).casefold()


def _abs(path: Path, root: Path) -> Path:
    return path if path.is_absolute() else root / path


def _rel_text(path: Path, root: Path) -> Optional[str]:
    """``path`` relative to ``root`` as an os-separated string (None when it is outside; "" for the root itself).
    String work only: this runs for every file of a big scan and pathlib's ``relative_to`` was the planner's hot spot."""
    text, base = os.fspath(path), os.fspath(root)
    if text == base:
        return ""
    if base.endswith(os.sep):                # the filesystem root
        return text[len(base):] if text.startswith(base) else None
    return text[len(base) + 1:] if text.startswith(base + os.sep) else None


def _rel_to(path: Path, root: Path) -> Optional[Path]:
    text = _rel_text(path, root)
    return None if text is None else Path(text)


def _add_reason(op: RenameOp, extra: str) -> None:
    op.reason = f"{op.reason}, {extra}" if op.reason else extra


# --------------------------------------------------------------------------- planning


def _parts_of(path: Path, root: Path) -> tuple[str, ...]:
    text = _rel_text(path, root)
    return tuple(text.split(os.sep)) if text else ()


def _is_reserved_path(path: Path, root: Path) -> bool:
    """True for files inside one of the reserved app folders (:data:`folders.RESERVED_DIRS`)."""
    return folders.classify(_parts_of(path, root)) is not None


def _legacy_folder(path: Path, root: Path) -> Optional[str]:
    """The reserved folder of a file still in the legacy layout (``_unmatched/_excluded/...``), else None."""
    info = folders.classify(_parts_of(path, root))
    return info[0] if info is not None and info[1] else None


def _is_converted_original(path: Path, root: Path) -> bool:
    """True for files under ``_converted_originals/`` (kept by convert.py; also the legacy place)."""
    return folders.is_converted(_parts_of(path, root))


def _is_keep_file(path: Path) -> bool:
    name = path.name.casefold()
    return name in KEEP_NAMES or os.path.splitext(name)[1] in KEEP_SUFFIXES


def _finish_op(src: Path, dst: Path, reasons: list[str], rom_name: str, dat: str,
               unmatched: bool) -> RenameOp:
    at_target = src == dst or (src.name == dst.name and _same_file(src, dst))
    status = "ok" if at_target else "move"
    kind = "rename" if _fold(src.parent) == _fold(dst.parent) else "move"
    if at_target:
        dst = src
    return RenameOp(src, dst, status, ", ".join(reasons), rom_name, kind, dat, unmatched)


def _converted_op(src: Path, root: Path) -> RenameOp:
    """An original kept by Convert stays where it is; one in the legacy place moves to ``_converted_originals/``."""
    if _legacy_folder(src, root) is not None:
        dst = root.joinpath(CONVERTED_DIR, *folders.core_parts(_parts_of(src, root)))
        return RenameOp(src, dst, "move", "original kept by Convert", "", "move", "", True)
    return RenameOp(src, src, "ok", "original kept by Convert", "", "move", "", True)


class _Planner:
    """Per-plan settings for files that matched nothing."""

    def __init__(self, root: Path, missing_dats: Iterable[str],
                 layout: str = LAYOUT_PER_DAT) -> None:
        self.root = root
        self.layout = layout
        # The "folder of a DAT that is not loaded" rule only makes sense with DAT folders.
        self.missing_folders = ({dat_folder_name(n).casefold(): n for n in missing_dats if n}
                                if layout != LAYOUT_FLAT else {})

    def unmatched(self, src: Path, why: str) -> RenameOp:
        root = self.root
        if _is_converted_original(src, root):
            return _converted_op(src, root)
        info = folders.classify(_parts_of(src, root))
        if info is not None:
            name, legacy = info
            if legacy:   # a file in a reason folder of the old layout: the folder moves to the top level
                code = next((c for c, d in CODE_DIRS.items() if d == name), "")
                op = RenameOp(src, root.joinpath(name, *folders.core_parts(_parts_of(src, root))), "move", why,
                              "", "move", "", True)
                op.code = code
                return op
            return RenameOp(src, src, "ok", f"{why}, already in {name}", "", "move", "", True)
        rel = _rel_to(src, root)
        if rel is None:
            return RenameOp(src, src, "skip", "outside the selected folder", "", "move", "", True)
        if len(rel.parts) > 1 and rel.parts[0].casefold() in self.missing_folders:
            dat = self.missing_folders[rel.parts[0].casefold()]
            return RenameOp(src, src, "skip", f"{why}, but the DAT '{dat}' is not loaded - left in its folder",
                            "", "move", "", True)
        if self.layout == LAYOUT_FLAT and len(rel.parts) > 1 and rel.parts[0].casefold() in KEEP_DIRS:
            return RenameOp(src, src, "skip", "frontend media folder - left in place", "", "move", "", True)
        if _is_keep_file(src):
            return RenameOp(src, src, "skip", "frontend / emulator file - left in place", "", "move", "", True)
        return _finish_op(src, root / UNMATCHED_DIR / rel, [why], "", "", True)


def _matched_op(src: Path, root: Path, roms: Sequence["Rom"], archive_ext: Optional[str],
                layout: str = LAYOUT_PER_DAT, matched_via: str = "raw",
                byte_order: str = "") -> tuple[RenameOp, "Rom"]:
    """Op for a loose file (``archive_ext`` None) or a single-game archive, and its rom."""
    if archive_ext is None:
        rom, alts = choose_rom(src.name, roms,
                               key=lambda r: _target_name(r, src.name, None, matched_via, byte_order))
    else:
        stem, _ = _split_ext(src.name)
        rom, alts = choose_rom(stem, roms, key=_archive_stem)
        alts = [r for r in alts if _archive_stem(r) != _archive_stem(rom)]
    target = _target_name(rom, src.name, archive_ext, matched_via, byte_order)
    reasons: list[str] = []
    safe = safe_filename(target)
    if safe != target:
        reasons.append("sanitised for filesystem")
    if matched_via == "headerless":
        reasons.append("matched with its header skipped (file kept as is)")
    elif matched_via == "byteswapped":
        reasons.append(f"matched byte-swapped{f' ({byte_order})' if byte_order else ''} (file kept as is)")
    if alts:
        reasons.append("alternatives: " + "; ".join(r.name for r in alts[:5])
                       + (" ..." if len(alts) > 5 else ""))
    dst = canonical_dir(root, rom.dat, layout) / safe
    return _finish_op(src, dst, reasons, rom.name, rom.dat, False), rom


HEADERLESS_EXTS = {".unh"}  # DAT roms without the header emulators need (NES)


def _header_form(rom: "Rom", matched_via: str) -> str:
    """``"headerless"`` for a file that *is* a headerless dump (raw match of a ``.unh`` rom),
    else ``""``. Latest-only compares versions only within one form, so a newer headerless
    ``.unh`` never sends away the only playable (iNES-headered) copy of a game."""
    if matched_via == "raw" and _split_ext(rom.name)[1].lower() in HEADERLESS_EXTS:
        return "headerless"
    return ""


def reason_destination(src: Path, root: Path, reason_dir: str) -> Path:
    """``root/<reason_dir>/<rel_core>``: ``rel_core`` is the path relative to ``root`` with a leading
    reserved folder (``_unmatched/``, ``_excluded/`` ... or the legacy ``_unmatched/_excluded/``)
    removed. The file name is unchanged, so a file already in another reason folder keeps its place
    in the tree."""
    rel = _rel_to(src, root)
    if rel is None:
        raise ValueError(f"path outside the folder: {src}")
    return root.joinpath(reason_dir, *folders.core_parts(rel.parts))


@dataclass
class MatchedUnit:
    """One matched file the organiser treats as one game: a loose file, or an archive whose members
    all match one game of one DAT (see :func:`matched_units`)."""

    path: Path                 # absolute
    op: RenameOp               # its canonical op (move / ok / conflict later)
    rom: "Rom"                 # the rom chosen by :func:`choose_rom`
    key: frozenset             # {unit_key(rom)} of the primary roms the file stands for
    form: str                  # :func:`_header_form`
    dat: str
    raw: bool                  # exact DAT content (not an alternate-hash match)
    archive: bool
    link: bool                 # symbolic link: never touched
    member: Optional[str] = None
    members: int = 1
    style: str = "tosec"


def _collect(result: "ScanResult", root: Path) -> tuple[dict[Path, "Match"], set[Path],
                                                       dict[Path, list[tuple["Entry", Optional["Match"]]]]]:
    loose_matched: dict[Path, "Match"] = {}
    loose_unmatched: set[Path] = set()
    archives: dict[Path, list[tuple["Entry", Optional["Match"]]]] = {}
    for m in result.matched:
        p = _abs(m.entry.path, root)
        if m.entry.member is None:
            loose_matched.setdefault(p, m)
        else:
            archives.setdefault(p, []).append((m.entry, m))
    for e in result.unmatched:
        p = _abs(e.path, root)
        if e.member is None:
            loose_unmatched.add(p)
        else:
            archives.setdefault(p, []).append((e, None))
    return loose_matched, loose_unmatched, archives


def _scan_units(result: "ScanResult", layout: Optional[str] = None,
                planner: Optional[_Planner] = None) -> tuple[list[MatchedUnit], list[RenameOp]]:
    """``(units, other ops)``; ``other ops`` (unmatched / skipped / converted originals / unsupported /
    unreadable files) are only built when a ``planner`` is given.

    The planner-independent part (the units) is worked out once per scan result and layout and handed out as copies:
    the plan edits its ops, and every preview / total used to rebuild all of them."""
    root = result.root
    if layout is None:
        layout = getattr(result, "layout", LAYOUT_PER_DAT) or LAYOUT_PER_DAT
    units, others, unmatched_loose, unmatched_archives = _base_units(result, layout)
    units = [dataclasses.replace(u, op=copy.copy(u.op)) for u in units]
    others = [copy.copy(o) for o in others]
    if planner is not None:
        for p in unmatched_loose:
            others.append(planner.unmatched(p, "no DAT match"))
        for p, why in unmatched_archives:
            others.append(planner.unmatched(p, why))
        for p in result.unsupported:
            others.append(planner.unmatched(_abs(Path(p), root), "unsupported archive (7z not found)"))
        for p, msg in result.errors:
            ap = _abs(Path(p), root)
            others.append(RenameOp(ap, ap, "skip", f"could not be read: {msg}"))
    return units, others


def _base_units(result: "ScanResult", layout: str) -> tuple[list[MatchedUnit], list[RenameOp], list[Path], list[tuple[Path, str]]]:
    if not getattr(result, "cache_units", False):    # only the server, which never edits a finished scan, opts in
        return _build_units(result, layout)
    cache = result.__dict__.setdefault("_base_units_cache", {})
    if layout not in cache:
        cache[layout] = _build_units(result, layout)
    return cache[layout]


def _build_units(result: "ScanResult", layout: str) -> tuple[list[MatchedUnit], list[RenameOp], list[Path], list[tuple[Path, str]]]:
    from .datfile import unit_key

    root = result.root
    loose_matched, loose_unmatched, archives = _collect(result, root)
    units: list[MatchedUnit] = []
    others: list[RenameOp] = []
    unmatched_archives: list[tuple[Path, str]] = []

    def style_of(rom: "Rom") -> str:
        from .tags import style_of_rom
        return style_of_rom(rom)

    for p, m in loose_matched.items():
        if _is_converted_original(p, root):
            others.append(_converted_op(p, root))
            continue
        via = getattr(m, "matched_via", "raw") or "raw"
        op, rom = _matched_op(p, root, m.primary, None, layout, via, getattr(m, "byte_order", "") or "")
        units.append(MatchedUnit(p, op, rom, frozenset(unit_key(r) for r in m.primary), _header_form(rom, via),
                                 rom.dat, via == "raw", False, os.path.islink(p), None, 1, style_of(rom)))
    unmatched_loose = sorted(loose_unmatched - set(loose_matched), key=os.fspath)

    for p, members in archives.items():
        if _is_converted_original(p, root):
            others.append(_converted_op(p, root))
            continue
        matches = [m for _, m in members if m is not None]
        n = len(members)
        _, ext = _split_ext(p.name)
        if not matches:
            unmatched_archives.append((p, "no DAT match" if n == 1 else f"none of {n} members match"))
            continue
        if len(matches) == n:
            # All members matched: usable if they belong to one game (set) of one DAT.
            dat = matches[0].dat
            games: Optional[set[str]] = None
            for m in matches:
                g = {_archive_stem(r) for r in m.primary} if m.dat == dat else set()
                games = g if games is None else games & g
            if games:
                roms = [r for r in matches[0].primary if _archive_stem(r) in games]
                op, rom = _matched_op(p, root, roms, ext, layout)
                if n > 1:
                    _add_reason(op, f"archive holds {n} roms of one game")
                via = getattr(matches[0], "matched_via", "raw") or "raw"
                key = frozenset(unit_key(r) for m in matches for r in m.primary if _archive_stem(r) in games)
                units.append(MatchedUnit(p, op, rom, key, _header_form(rom, via), rom.dat, via == "raw",
                                         True, os.path.islink(p), members[0][0].member, n, style_of(rom)))
                continue
        others.append(RenameOp(p, p, "skip", f"archive has {n} members ({len(matches)} matched)"))
    return units, others, unmatched_loose, unmatched_archives


def matched_units(result: "ScanResult", layout: Optional[str] = None) -> list[MatchedUnit]:
    """The matched files the organiser treats as one game each (originals kept by Convert excluded).
    :func:`scanner.duplicate_groups` groups these."""
    return _scan_units(result, layout)[0]


def _platform_for(result: "ScanResult", platform: Any = None) -> Any:
    """The platform whose DATs the scan used (``platform`` if given), else a generic stand-in
    where "latest versions" applies to every DAT."""
    if platform is not None:
        return platform
    names = set(getattr(result, "dat_names", ()) or ())
    try:
        from .platforms import list_platforms

        for p in list_platforms():
            if names and names <= set(p.dats):
                return p
    except Exception:  # platforms unavailable: use the stand-in
        pass
    from types import SimpleNamespace

    dats = tuple(getattr(result, "dat_names", ()) or ())
    return SimpleNamespace(name="", dats=dats, latest_dats=dats, best_variant_dats=(), m3u_dats=())


def _send_to_reason(op: RenameOp, root: Path, code: str, why: str, keeper: str = "",
                    missing: tuple[int, ...] = (), flags_text: str = "", superseded_by: str = "",
                    reasons: tuple[str, ...] = ()) -> None:
    """Turn ``op`` into a move to ``<reason dir>/<rel path>`` (``ok`` if it is already there)."""
    reason_dir = CODE_DIRS[code]
    dst = reason_destination(op.src, root, reason_dir)
    new = _finish_op(op.src, dst, [], op.rom_name, op.dat, True)
    op.dst, op.status, op.kind, op.unmatched = new.dst, new.status, new.kind, True
    op.reason = why + (f", already in {reason_dir}" if new.status == "ok" else "")
    op.code, op.keeper, op.missing, op.flags_text, op.superseded_by = code, keeper, tuple(missing), flags_text, superseded_by
    op.reasons = tuple(reasons)


class _Core:
    """Result of one planning run (shared by :func:`plan_renames` and :func:`plan_library`)."""

    def __init__(self, ops: list[RenameOp], selection: Optional["library.Selection"],
                 owners: dict[int, tuple[RenameOp, MatchedUnit]]) -> None:
        self.ops, self.selection, self.owners = ops, selection, owners


def _plan_core(result: "ScanResult", missing_dats: Iterable[str], latest_only: bool,
               layout: Optional[str], profile: Optional["library.LibraryProfile"], platform: Any,
               ratings: Any = None) -> _Core:
    from . import scanner

    root = result.root
    if layout is None:
        layout = getattr(result, "layout", LAYOUT_PER_DAT) or LAYOUT_PER_DAT
    planner = _Planner(root, missing_dats, layout)
    units, others = _scan_units(result, layout, planner)
    ops: list[RenameOp] = [u.op for u in units] + others
    links = {id(u.op) for u in units if u.link}        # the units already know (one lstat per file, done once)
    known = {id(u.op) for u in units}
    for op in ops:
        if op.status in MOVE_STATUSES and (id(op) in links if id(op) in known else os.path.islink(op.src)):
            op.status, op.dst, op.reason = "skip", op.src, "symbolic link - left in place"

    # Duplicates first (independent of the library rules): one keeper per rom, spare copies set aside.
    by_path = {u.path: u for u in units}
    losers: set[Path] = set()
    for keeper, group in scanner.duplicate_groups(result, layout, units=units):
        keeper_rel = _rel_to(keeper, root)
        keeper_text = keeper_rel.as_posix() if keeper_rel is not None else str(keeper)
        for path in group:
            u = by_path.get(path)
            if u is None:
                continue
            losers.add(path)
            _send_to_reason(u.op, root, "duplicate", f"duplicate of {keeper_text}", keeper=keeper_text)

    selection = None
    owners: dict[int, tuple[RenameOp, MatchedUnit]] = {}
    if profile is None and latest_only:
        from . import library

        profile = library.LibraryProfile.latest_only_profile()
    if profile is not None:
        from . import library

        items = []
        have_rom = {(u.dat, u.rom.name) for u in units if not u.link and u.path not in losers}
        for u in units:
            if u.path in losers:
                continue
            if u.link:
                if (u.dat, u.rom.name) in have_rom:
                    continue      # a real file already stands for this rom
                have_rom.add((u.dat, u.rom.name))
            key = len(items)
            owners[key] = (u.op, u)
            items.append(library.Item(key, u.dat, u.rom, u.style, u.path, u.member, u.form, u.link))
        selection = library.select(items, profile, _platform_for(result, platform), ratings=ratings)
        for key, (op, u) in owners.items():
            d = selection.decisions.get(key)
            if d is not None and d.action == library.KEEP and library.BORROWED_CODE in d.codes and not u.link:
                _add_reason(op, d.reason.split("; ")[-1])      # "borrowed as disk N of <set> (...)"
            if d is None or d.action == library.KEEP:
                continue
            code = d.action
            if code not in CODE_DIRS or u.link:
                continue          # a symlink fills slots / ranks like any file but is never moved
            _send_to_reason(op, root, code, d.reason or code, missing=d.missing, flags_text=d.detail,
                            superseded_by=d.superseded_by, reasons=tuple(d.codes))

    ops.sort(key=lambda o: (o.unmatched, o.dat, str(o.src).casefold()))
    _resolve_conflicts(ops, root)
    for op in ops:   # legacy layout: say why the file leaves _unmatched/<reason>/ ; record the target folder
        if op.status in MOVE_STATUSES:
            legacy = _legacy_folder(op.src, root)
            if legacy is not None:
                _add_reason(op, f"moved out of {UNMATCHED_DIR}/{legacy}/ (new layout)")
        op.folder = folders.top_folder(_parts_of(op.dst, root)) or ""
    ops.extend(_plan_m3u_ops(ops, root))
    return _Core(ops, selection, owners)


def plan_renames(result: "ScanResult", missing_dats: Iterable[str] = (),
                 latest_only: bool = False,
                 layout: Optional[str] = None, profile: Optional["library.LibraryProfile"] = None,
                 platform: Any = None) -> list[RenameOp]:
    """Build one op for every file found by the scan (matched, unmatched, unsupported, errors).

    ``missing_dats``: DAT names of the platform that were not loaded; unmatched
    files inside their folders are left alone (``skip``) instead of being swept
    into ``_unmatched/`` (``per_dat`` layout only). Unmatched files are always moved. ``layout`` (``"per_dat"`` | ``"flat"``) defaults to ``result.layout``.
    Files under ``_converted_originals/`` are always left alone (``ok``; the legacy
    ``_unmatched/_converted_originals/`` moves there).
    Our own m3u playlists that reference moving files get a ``delete`` op.

    Spare copies of one rom (same content, loose or archived) go to ``_duplicates/``
    (always; see :func:`scanner.duplicate_groups` for the keeper). With a library ``profile``
    (``latest_only=True`` stands for ``LibraryProfile.latest_only_profile()``) files the profile
    excludes / supersedes / finds incomplete go to ``_excluded/`` / ``_superseded/`` /
    ``_incomplete/`` (``<path relative to root>``, file name unchanged); a file there that no
    longer qualifies moves back to its canonical place. ``platform`` (default: found from the
    scan's DAT names) tells the profile which DATs each rule covers.
    """
    return _plan_core(result, missing_dats, latest_only, layout, profile, platform).ops


def _final_path(op: RenameOp) -> Path:
    return op.dst if (op.status in MOVE_STATUSES or op.status == "ok") else op.src


@dataclass
class LibraryPlan:
    """One preview for "Build library": file moves, playlist writes and removals, and why."""

    ops: list[RenameOp]                  # file moves + ``delete`` ops for stale own playlists
    playlists: list["m3u.M3UOp"]         # write | ok | conflict
    selection: "library.Selection"
    profile: "library.LibraryProfile"

    def counts(self) -> dict[str, int]:
        out = plan_counts(self.ops)
        for k, v in reason_counts(self).items():
            if k.startswith("playlists_"):
                out[k] = v
        return out

    def exclusion_counts(self) -> dict[str, dict[str, int]]:
        """Excluded files per reason code (``library.Selection.exclusion_counts``: ``exclusive`` / ``any``)."""
        return self.selection.exclusion_counts()

    def vanish_summary(self) -> dict:
        """Titles none of whose variants is kept: ``{"titles", "by_reason", "by_code"}``."""
        return self.selection.vanish_summary()

    @property
    def vanished(self) -> list["library.Vanished"]:
        return self.selection.vanished


def plan_library(result: "ScanResult", profile: "library.LibraryProfile", missing_dats: Iterable[str] = (),
                 layout: Optional[str] = None, savedisk: bool = False,
                 labels: bool = True, platform: Any = None, ratings: Any = None) -> LibraryPlan:
    """See :func:`_plan_library`; playlists on disk are looked at once for the whole plan (``m3u.one_look``)."""
    from . import m3u

    with m3u.one_look():
        return _plan_library(result, profile, missing_dats, layout, savedisk, labels, platform, ratings)


def _plan_library(result: "ScanResult", profile: "library.LibraryProfile", missing_dats: Iterable[str] = (),
                 layout: Optional[str] = None, savedisk: bool = False,
                 labels: bool = True, platform: Any = None, ratings: Any = None) -> LibraryPlan:
    """The combined plan: tidy + duplicates + the profile's rules + playlists of the kept multi-disk sets.

    Playlists are planned from the disks' FINAL paths (next to disk 1). Our own playlists that go
    stale (disks move away or are gone, or a planned playlist replaces them) get ``delete`` ops; one
    that is deleted and rewritten under the same name becomes a single ``write``.
    """
    from . import library, m3u

    core = _plan_core(result, missing_dats, False, layout, profile, platform, ratings)
    root = result.root
    ops = core.ops
    sel = core.selection if core.selection is not None else library.Selection()

    specs: list["m3u.PlaylistSpec"] = []
    counts: dict[str, int] = {}
    for cs in sel.sets:
        disks = []
        for slot, key in sorted(cs.slots.items()):
            owner = core.owners.get(key)
            if owner is None:
                continue
            op, unit = owner
            final = _final_path(op)
            if unit.archive and unit.members > 1:
                counts[str(final)] = unit.members
            disks.append(m3u.PlaylistDisk(slot, final, unit.member if unit.archive else None,
                                          cs.labels.get(slot, "")))
        if len(disks) == len(cs.slots) and disks:
            specs.append(m3u.PlaylistSpec(cs.name, cs.dat, cs.total, disks,
                                          [b["text"] for _i, b in sorted(cs.borrowed.items())]))
    playlists = m3u.plan_playlists(specs, root, savedisk=savedisk, labels=labels, member_counts=counts)

    moving = [str(op.src) for op in ops if op.status in MOVE_STATUSES]
    rewritten = {_fold(p.path) for p in playlists if p.status in ("write", "ok")}
    kept_ops: list[RenameOp] = []
    deleting: set[str] = set()
    by_src = {_fold(o.src): o for o in ops if o.kind != "m3u"}
    for op in ops:
        if op.status == DELETE_STATUS and op.kind == "m3u":
            if _fold(op.src) in rewritten:
                continue
            deleting.add(_fold(op.src))
            op.reason = _library_delete_reason(op, by_src)
        kept_ops.append(op)
    for st in m3u.plan_stale(root, playlists, moving):
        if _fold(st.path) in deleting or _fold(st.path) in rewritten:
            continue
        deleting.add(_fold(st.path))
        kept_ops.append(RenameOp(st.path, st.path, DELETE_STATUS, st.reason, "", "m3u"))
    return LibraryPlan(kept_ops, playlists, sel, profile)


def _library_delete_reason(op: RenameOp, by_src: dict[str, RenameOp]) -> str:
    """Why Build library removes one of our playlists (its disks move away - nothing is "written again")."""
    from . import m3u

    info = m3u.read_m3u(op.src)
    moved = [by_src[_fold(e)] for e in (info[1] if info else []) if _fold(e) in by_src
             and by_src[_fold(e)].status in MOVE_STATUSES and by_src[_fold(e)].code]
    if not moved:
        return op.reason
    missing = sorted({m for o in moved if o.code == "incomplete" for m in o.missing})
    if missing:
        return (f"set incomplete (missing disk {', '.join(str(m) for m in missing)}) - playlist removed; "
                "undo restores it")
    codes = sorted({o.code for o in moved})
    return (f"{len(moved)} of its disks are set aside ({', '.join(codes)}) - playlist removed; "
            "undo restores it")


def _relocate_duplicate(holder: RenameOp, root: Path, claimed: dict[str, RenameOp]) -> bool:
    """Send a duplicate that blocks another file's target to ``_unmatched/``; True if possible."""
    rel = _rel_to(holder.src, root)
    if rel is None or _is_reserved_path(holder.src, root):
        return False
    new_dst = root / UNMATCHED_DIR / rel
    key = _fold(new_dst)
    if key in claimed or _exists(new_dst):
        return False
    holder.status, holder.dst, holder.unmatched, holder.kind = "move", new_dst, True, "move"
    _add_reason(holder, f"moved to {UNMATCHED_DIR}/ because it sits at another file's name")
    claimed[key] = holder
    return True


def _free_reason_targets(ops: list[RenameOp]) -> None:
    """Give every move into a ``_<reason>/`` folder a target nobody else holds.

    Reason destinations keep the file name, so two files with one relative path (or one that
    already sits at the target) would clash and the spare would stay where it is forever. They
    get ``name (2).ext``, ``name (3).ext`` ... instead. Nothing is ever merged or overwritten."""
    moving_away = {_fold(op.src) for op in ops if op.status in MOVE_STATUSES}
    taken = {_fold(op.dst) for op in ops if op.status not in MOVE_STATUSES}
    taken |= {_fold(op.dst) for op in ops if op.status in MOVE_STATUSES and not op.code}
    coded = [op for op in ops if op.status in MOVE_STATUSES and op.code]
    # a file that already carries the plain name has first claim on it
    for op in sorted(coded, key=lambda o: (str(o.src).casefold(), str(o.src))):
        key = _fold(op.dst)
        if key not in taken and (not _exists(op.dst) or key in moving_away or _same_file(op.src, op.dst)):
            taken.add(key)
            continue
        stem, ext = _split_ext(op.dst.name)
        n = 2
        while True:
            cand = op.dst.with_name(f"{stem} ({n}){ext}")
            ckey = _fold(cand)
            if ckey not in taken and ckey not in moving_away and not _exists(cand):
                break
            n += 1
        op.dst = cand
        taken.add(ckey)
        _add_reason(op, f"renamed to {cand.name}: the name is already taken there")


def _resolve_conflicts(ops: list[RenameOp], root: Optional[Path] = None) -> None:
    """Mark conflicts/duplicates between ops and against files already on disk."""
    _free_reason_targets(ops)
    # Files whose current path is going away.
    moving_away = {_fold(op.src) for op in ops if op.status in MOVE_STATUSES}
    by_src = {_fold(op.src): op for op in ops}
    # Targets held by files that stay where they are.
    staying = {_fold(op.dst): op for op in ops if op.status not in MOVE_STATUSES}
    claimed: dict[str, RenameOp] = {}
    relies: list[tuple[RenameOp, str]] = []  # ops that need another op to free their target

    # Files that already carry the target name get first claim on it.
    for op in sorted(ops, key=lambda o: (o.src.name != o.dst.name, str(o.src).casefold())):
        if op.status not in MOVE_STATUSES:
            continue
        key = _fold(op.dst)
        extra = ""
        holder = claimed.get(key) or staying.get(key)
        if holder is not None:
            if _same_content(op.src, holder.src):
                op.status, extra = "duplicate", f"same content as {holder.src.name}"
            else:
                op.status, extra = "conflict", f"target also wanted by {holder.src.name}"
        elif _exists(op.dst) and not _same_file(op.src, op.dst):
            if key in moving_away:
                extra = "target is moved away first"
                relies.append((op, key))
            elif op.dst.is_dir():
                op.status, extra = "conflict", "a directory exists at target"
            elif _same_content(op.src, op.dst):
                op.status, extra = "duplicate", "identical file already exists at target"
            else:
                op.status, extra = "conflict", "a different file exists at target"
        elif op.src.name != op.dst.name and op.src.name.casefold() == op.dst.name.casefold():
            extra = "case-only rename"
        if op.status in MOVE_STATUSES:
            claimed[key] = op
        if extra:
            _add_reason(op, extra)

    # Fixpoint: an op relying on its target being moved away fails if that file
    # ended up staying (duplicate / conflict). Duplicates are moved out of the way.
    changed = True
    while changed:
        changed = False
        for op, key in relies:
            if op.status not in MOVE_STATUSES:
                continue
            holder = by_src.get(key)
            if holder is None or holder.status in MOVE_STATUSES:
                continue
            changed = True
            if holder.status == "duplicate" and root is not None and _relocate_duplicate(holder, root, claimed):
                continue
            op.reason = ", ".join(r for r in op.reason.split(", ") if r != "target is moved away first")
            op.status = "conflict"
            _add_reason(op, f"target is occupied by {holder.src.name}, which stays ({holder.status})")
            if claimed.get(_fold(op.dst)) is op:
                del claimed[_fold(op.dst)]


def _plan_m3u_ops(ops: list[RenameOp], root: Path) -> list[RenameOp]:
    """``delete`` ops for our own playlists whose disks move (or are gone); ``skip`` notes
    for user playlists whose disks move."""
    from . import m3u  # local import: m3u imports this module

    moving = {_fold(op.src) for op in ops if op.status in MOVE_STATUSES}
    out: list[RenameOp] = []
    for path in m3u.find_m3us(root):
        info = m3u.read_m3u(path)
        if info is None:
            continue
        own, entries = info
        hits = [e for e in entries if _fold(e) in moving]
        if own:
            if hits:
                out.append(RenameOp(path, path, DELETE_STATUS,
                                    f"playlist made by this app; {len(hits)} of its disks move - "
                                    "write the M3Us again afterwards", "", "m3u"))
            elif entries and not any(_exists(e) for e in entries):
                out.append(RenameOp(path, path, DELETE_STATUS,
                                    "stale playlist made by this app (its disks are gone)", "", "m3u"))
        elif hits:
            out.append(RenameOp(path, path, "skip",
                                f"your playlist: {len(hits)} of its disks move - update it afterwards",
                                "", "m3u"))
    return out


def plan_counts(ops: Iterable[RenameOp]) -> dict[str, int]:
    """Counts by status plus ``to_unmatched`` (files that will move into ``_unmatched/``) and
    ``to_excluded`` / ``to_superseded`` / ``to_duplicates`` / ``to_incomplete`` (files moving into
    that reason folder; separate folders since Amendment 9)."""
    out: dict[str, int] = {}
    for op in ops:
        out[op.status] = out.get(op.status, 0) + 1
        if op.unmatched and op.status in MOVE_STATUSES:
            if op.code in CODE_DIRS:
                k = {"duplicate": "to_duplicates"}.get(op.code, f"to_{op.code}")
                out[k] = out.get(k, 0) + 1
            elif op.folder in ("", UNMATCHED_DIR):
                out["to_unmatched"] = out.get("to_unmatched", 0) + 1
    for k in ("to_unmatched", "to_excluded", "to_superseded", "to_duplicates", "to_incomplete"):
        out.setdefault(k, 0)
    return out


def reason_counts(plan: "LibraryPlan") -> dict[str, int]:
    """Preview cards of a :class:`LibraryPlan`: ``kept`` (matched files that end up in their canonical
    place, ``renamed`` / ``moved`` = of those, the ones that change), ``excluded`` / ``superseded`` /
    ``incomplete`` / ``duplicates`` (files moving there), ``unmatched`` (no-match files moving into
    ``_unmatched/``), ``conflict``, ``skip`` and the playlists (``playlists_write`` / ``_ok`` /
    ``_remove`` / ``_conflict``). ``excluded_<code>`` splits ``excluded`` by each file's PRIMARY reason
    (``bad_dump`` ... ``modified``, ``flag_cr`` ... ``flag_tr``, ``language``; always present, sums to
    ``excluded``)."""
    from . import library

    out = dict.fromkeys(("kept", "renamed", "moved", "excluded", "superseded", "incomplete", "duplicates",
                         "unmatched", "conflict", "skip", "playlists_write", "playlists_ok",
                         "playlists_remove", "playlists_conflict"), 0)
    out.update(dict.fromkeys((f"excluded_{c}" for c in library.ALL_CODES), 0))
    borrow = plan.selection.borrow_summary()
    out["borrowed_sets"], out["borrowed_disks"] = borrow["sets"], borrow["disks"]
    for op in plan.ops:
        if op.status == DELETE_STATUS:
            out["playlists_remove"] += 1
        elif op.status in ("conflict", "skip"):
            out[op.status] += 1
        elif op.code:
            if op.status in MOVE_STATUSES:
                out["duplicates" if op.code == "duplicate" else op.code] += 1
                if op.code == "excluded":
                    key = f"excluded_{op.reasons[0]}" if op.reasons else "excluded_other"
                    out[key] = out.get(key, 0) + 1
        elif op.unmatched:
            if op.status in MOVE_STATUSES and op.folder in ("", UNMATCHED_DIR):
                out["unmatched"] += 1
        elif op.status in MOVE_STATUSES or op.status in ("ok", "duplicate"):
            out["kept"] += 1
            if op.status in MOVE_STATUSES:
                out["renamed" if op.kind == "rename" else "moved"] += 1
    for p in plan.playlists:
        key = f"playlists_{p.status}"
        if key in out:
            out[key] += 1
    return out


# --------------------------------------------------------------------------- moving


_NO_LINK_ERRNOS = {errno.EPERM, errno.EXDEV, errno.EMLINK, errno.ENOSYS,
                   getattr(errno, "ENOTSUP", -1), getattr(errno, "EOPNOTSUPP", -1)}


def _move_exclusive(src: Path, dst: Path) -> None:
    """Move src -> dst without ever replacing an existing dst.

    Uses ``link`` + ``unlink`` (atomic: fails if dst exists) where hard links are
    supported, else falls back to check-then-rename (FAT/exFAT).
    """
    try:
        os.link(src, dst, follow_symlinks=False)
    except FileExistsError:
        raise FileExistsError(f"target exists: {dst}") from None
    except (NotImplementedError, AttributeError):
        pass
    except OSError as exc:
        if exc.errno not in _NO_LINK_ERRNOS:
            raise
    else:
        try:
            os.unlink(src)
        except OSError:
            try:
                os.unlink(dst)
            except OSError:
                pass
            raise
        return
    if _exists(dst):
        raise FileExistsError(f"target exists: {dst}")
    os.rename(src, dst)


def _temp_name(p: Path) -> Path:
    return p.with_name(f"{p.name}{TEMP_MARKER}{uuid.uuid4().hex[:8]}")


def _rename_no_overwrite(src: Path, dst: Path) -> None:
    """Rename src -> dst, refusing to overwrite. Case-only renames use a temp name."""
    if not _exists(src):
        raise FileNotFoundError(f"source missing: {src}")
    if _exists(dst):
        if not _same_file(src, dst):
            raise FileExistsError(f"target exists: {dst}")
        # Case-insensitive FS and only the case differs: go via a temporary name.
        tmp = _temp_name(src)
        os.rename(src, tmp)
        try:
            if _exists(dst) and not _same_file(tmp, dst):
                raise FileExistsError(f"target exists: {dst}")
            _move_exclusive(tmp, dst)
        except BaseException:
            os.rename(tmp, src)
            raise
        return
    _move_exclusive(src, dst)


# --------------------------------------------------------------------------- undo log


def _rel_str(path: Path, root: Path) -> str:
    rel = _rel_to(Path(path), root)
    if rel is None or rel == Path("."):
        raise ValueError(f"path outside the folder: {path}")
    return rel.as_posix()


class UndoLogError(RuntimeError):
    """The undo log could not be written: no further changes are made."""


class _Journal:
    """Undo log written as JSON lines *before* each step (opened lazily)."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.path: Optional[Path] = None
        self._f: Optional[IO[str]] = None
        self._unsynced = 0
        self._seq = 0
        self.useful = False  # True once a recorded step actually happened

    def _open(self) -> None:
        self.path = _new_log_path(self.root)
        try:
            self._f = open(self.path, "x", encoding="utf-8", newline="\n")
        except OSError as exc:
            raise UndoLogError(f"cannot create the undo log: {exc}") from exc
        self._write({"version": LOG_VERSION, "root": str(self.root),
                     "started": datetime.now().isoformat(timespec="seconds")}, sync=True)

    def _write(self, record: dict[str, Any], sync: bool = False) -> None:
        assert self._f is not None
        try:
            self._f.write(json.dumps(record, ensure_ascii=True) + "\n")
            self._f.flush()  # survives a killed process; fsync below covers power loss
            self._unsynced += 1
            if sync or self._unsynced >= FSYNC_EVERY:
                os.fsync(self._f.fileno())
                self._unsynced = 0
        except OSError as exc:
            raise UndoLogError(f"cannot write the undo log: {exc}") from exc

    def record(self, record: dict[str, Any], sync: bool = False) -> int:
        """Append a record; returns its sequence number (for :meth:`failed`)."""
        if self._f is None:
            self._open()
        self._seq += 1
        self._write({**record, "i": self._seq}, sync)
        return self._seq

    def failed(self, seq: int) -> None:
        self._write({"op": "failed", "i": seq})

    def close(self) -> Optional[Path]:
        """Finish the log; remove it if nothing it recorded actually happened."""
        if self._f is None:
            return None
        try:
            self._write({"op": "end"}, sync=True)
        except UndoLogError:
            pass
        finally:
            try:
                self._f.close()
            except OSError:
                pass
            self._f = None
        assert self.path is not None
        if not self.useful:
            try:
                self.path.unlink()
            except OSError:
                pass
            return None
        return self.path


def _new_log_path(root: Path) -> Path:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = root / f"{UNDO_PREFIX}{stamp}.json"
    n = 1
    while path.exists():
        path = root / f"{UNDO_PREFIX}{stamp}-{n}.json"
        n += 1
    return path


def _inside(path: Path, root: Path, seen: Optional[dict[str, Optional[str]]] = None) -> bool:
    """True when ``path``'s real parent directory lies inside ``root`` (no symlink escapes).

    ``seen``: real paths already resolved during this one read of a log (a log names the same folders thousands of
    times, and resolving walks every path component on disk)."""
    def real(p: Any) -> Optional[str]:
        key = os.fspath(p)
        if seen is None:
            try:
                return os.path.realpath(key)
            except (OSError, ValueError):
                return None
        if key not in seen:
            out: Optional[str]
            parent, name = os.path.split(key)
            try:
                if not name or parent == key:
                    out = os.path.realpath(key)
                else:
                    # resolve the parent first (remembered): then only this one component can still be a link
                    above = real(parent)
                    here = None if above is None else os.path.join(above, name)
                    out = here if here is not None and not os.path.islink(here) else os.path.realpath(key)
            except (OSError, ValueError):
                out = None
            seen[key] = out
        return seen[key]

    real_root, real_parent = real(root), real(os.path.dirname(os.fspath(path)))
    if real_root is None or real_parent is None:
        return False
    return real_parent == real_root or real_parent.startswith(real_root.rstrip(os.sep) + os.sep)


def _resolve_logged(raw: Any, root: Path, old_root: Optional[str],
                    seen: Optional[dict[str, Optional[str]]] = None) -> Optional[Path]:
    """A logged path as an absolute path inside ``root``, or None if it is unsafe.

    Relative paths (v3) resolve against root; absolute ones (v1/v2) are rebased
    from the recorded root (the folder may have been remounted elsewhere).
    """
    if not isinstance(raw, str) or not raw:
        return None
    p = Path(raw)
    if p.is_absolute():
        rel = None
        for base in ([Path(old_root)] if old_root else []) + [root]:
            rel = _rel_to(p, base)
            if rel is not None:
                break
        if rel is None:
            return None
        parts = rel.parts
    else:
        parts = PurePosixPath(raw.replace("\\", "/")).parts
    if not parts or any(part in ("..", "") for part in parts) or Path(*parts).is_absolute():
        return None
    out = root.joinpath(*parts)
    return out if _inside(out, root, seen) else None


def read_undo_log(log_path: Path) -> dict[str, Any]:
    """Parse an undo log (v1 list, v2 JSON document or v3 JSON lines).

    Returns ``{"version", "moves": [{"src": Path, "dst": Path}], "created_files":
    [{"path": Path, "sha1": str, "size": int}], "steps": [...], "created_dirs": [Path],
    "removed_dirs": [Path], "deleted": [{"path": Path, "content": str}], "temp_files": [Path],
    "complete": bool, "rejected": int}``. ``temp_files``: Convert's temporary output files
    (``*.romorg-convert-*``, ``tmp`` records) - left behind only by an interrupted run. ``steps`` holds the move and create records in log order
    (``{"op": "move", "src", "dst"}`` / ``{"op": "create", "path", "sha1", "size"}``);
    ``moves`` is kept for compatibility. Paths are absolute, inside the log's folder;
    entries that would reach outside it are dropped and counted in ``rejected``.
    """
    log_path = Path(log_path)
    root = log_path.parent.absolute()
    seen: dict[str, Optional[str]] = {}       # real paths resolved while reading this log
    text = log_path.read_text(encoding="utf-8")
    records: list[dict[str, Any]] = []
    header: dict[str, Any] = {}
    data: Any = None
    try:
        data = json.loads(text)
    except ValueError:
        data = None
    if isinstance(data, list):  # version 1: plain list of {src, dst}
        header = {"version": 1}
        records = [{"op": "move", **m} for m in data if isinstance(m, dict)]
    elif isinstance(data, dict) and "moves" in data and data.get("version", 2) < 3:
        header = data
        records = [{"op": "move", **m} for m in data.get("moves", []) if isinstance(m, dict)]
        records += [{"op": "mkdir", "path": d} for d in data.get("created_dirs", [])]
        records += [{"op": "rmdir", "path": d} for d in data.get("removed_dirs", [])]
        records.append({"op": "end"})
    else:  # version 3: JSON lines, header first; a torn last line is ignored
        for n, line in enumerate(text.splitlines()):
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            if not isinstance(rec, dict):
                continue
            if n == 0 and "op" not in rec:
                header = rec
            else:
                records.append(rec)
    old_root = header.get("root") if isinstance(header.get("root"), str) else None
    failed = {r.get("i") for r in records if r.get("op") == "failed"}

    out: dict[str, Any] = {"version": header.get("version", LOG_VERSION), "moves": [], "created_files": [],
                           "steps": [], "created_dirs": [], "removed_dirs": [], "deleted": [],
                           "temp_files": [], "complete": False, "rejected": 0}
    created: dict[str, Path] = {}
    for rec in records:
        op = rec.get("op")
        if op == "end":
            out["complete"] = True
            continue
        if op == "failed" or ("i" in rec and rec["i"] in failed):
            continue
        if op == "move":
            src, dst = _resolve_logged(rec.get("src"), root, old_root, seen), _resolve_logged(rec.get("dst"), root, old_root, seen)
            if src is None or dst is None:
                out["rejected"] += 1
            else:
                out["moves"].append({"src": src, "dst": dst})
                out["steps"].append({"op": "move", "src": src, "dst": dst})
        elif op == "create":
            p = _resolve_logged(rec.get("path"), root, old_root, seen)
            sha1, size = rec.get("sha1"), rec.get("size")
            if (p is None or not isinstance(sha1, str) or not sha1
                    or not isinstance(size, int) or isinstance(size, bool)):
                out["rejected"] += 1
            else:
                item = {"path": p, "sha1": sha1.lower(), "size": size}
                out["created_files"].append(item)
                out["steps"].append({"op": "create", **item})
        elif op == "tmp":  # a temporary file Convert was about to write
            p = _resolve_logged(rec.get("path"), root, old_root, seen)
            if p is None or CONVERT_TEMP_MARKER not in p.name:
                out["rejected"] += 1
            else:
                out["temp_files"].append(p)
        elif op in ("mkdir", "unmkdir", "rmdir"):
            p = _resolve_logged(rec.get("path"), root, old_root, seen)
            if p is None:
                out["rejected"] += 1
            elif op == "mkdir":
                created[_fold(p)] = p
            elif op == "unmkdir":
                created.pop(_fold(p), None)
            else:
                out["removed_dirs"].append(p)
        elif op == "delete":
            p = _resolve_logged(rec.get("path"), root, old_root, seen)
            content = rec.get("content")
            if p is None or not isinstance(content, str):
                out["rejected"] += 1
            else:
                out["deleted"].append({"path": p, "content": content})
    out["created_dirs"] = list(created.values())
    return out


def _write_log(log_path: Path, root: Path, steps: list[dict[str, Any]], created: list[Path],
               deleted: list[dict[str, Any]], temps: Sequence[Path] = ()) -> None:
    """Rewrite a log atomically (v3) with what is still left to undo.

    ``steps``: remaining moves (``{"src", "dst"}``, optional ``"op": "move"``) and creates
    (``{"op": "create", "path", "sha1", "size"}``) in apply order.
    """
    lines = [json.dumps({"version": LOG_VERSION, "root": str(root),
                         "started": datetime.now().isoformat(timespec="seconds"), "partial": True})]
    for d in created:
        lines.append(json.dumps({"op": "mkdir", "path": _rel_str(d, root)}))
    for t in temps:
        lines.append(json.dumps({"op": "tmp", "path": _rel_str(t, root)}))
    for m in steps:
        if m.get("op") == "create":
            lines.append(json.dumps({"op": "create", "path": _rel_str(m["path"], root),
                                     "sha1": m["sha1"], "size": m["size"]}))
        else:
            lines.append(json.dumps({"op": "move", "src": _rel_str(m["src"], root),
                                     "dst": _rel_str(m["dst"], root)}))
    for d in deleted:
        lines.append(json.dumps({"op": "delete", "path": _rel_str(d["path"], root), "content": d["content"]}))
    lines.append(json.dumps({"op": "end"}))
    tmp = log_path.with_name(log_path.name + ".tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, log_path)


# --------------------------------------------------------------------------- applying


def _make_dirs(directory: Path, created: list[str], journal: Optional[_Journal] = None) -> None:
    """mkdir -p, recording each directory we actually create (outermost first)."""
    missing: list[Path] = []
    d = directory
    while not _exists(d):
        missing.append(d)
        if d.parent == d:
            break
        d = d.parent
    for d in reversed(missing):
        try:
            os.mkdir(d)
        except FileExistsError:
            continue
        created.append(str(d))
        if journal is not None:
            journal.record({"op": "mkdir", "path": _rel_str(d, journal.root)})


def _protected_dirs(root: Path, ops: Sequence[RenameOp], dat_names: Iterable[str]) -> set[str]:
    names = set(dat_names) | {op.dat for op in ops if op.dat}
    try:
        from .platforms import all_dat_names

        names |= all_dat_names()
    except Exception:  # platforms module unavailable: rely on the explicit names
        pass
    out = {_fold(root), _fold(root / UNMATCHED_DIR)}   # emptied reason folders may go; _unmatched/ stays
    out |= {_fold(root / dat_folder_name(n)) for n in names}
    return out


def _remove_empty_dirs(candidates: Iterable[Path], root: Path, protected: set[str]) -> list[str]:
    """rmdir candidates (and then their parents) that are empty; deepest first."""
    removed: list[str] = []
    todo = sorted({_abs(c, root) for c in candidates}, key=lambda p: len(p.parts), reverse=True)
    for d in todo:
        while _rel_to(d, root) not in (None, Path(".")) and _fold(d) not in protected:
            try:
                os.rmdir(d)  # fails unless empty: never removes content
            except OSError:
                break
            removed.append(str(d))
            d = d.parent
    return removed


def _is_cancelled(cancel: Any) -> bool:
    if cancel is None:
        return False
    if hasattr(cancel, "is_set"):
        return bool(cancel.is_set())
    return bool(cancel())


def _cycle_member(blocked: list[RenameOp]) -> Optional[RenameOp]:
    """A blocked op that is part of a real cycle (A->B, B->A ...), or None."""
    by_src = {_fold(o.src): o for o in blocked}
    for start in blocked:
        seen: set[int] = set()
        cur: Optional[RenameOp] = start
        while cur is not None and id(cur) not in seen:
            seen.add(id(cur))
            cur = by_src.get(_fold(cur.dst))
            if cur is start:
                return start
    return None


def _write_playlist(pl: "m3u.M3UOp", root: Path, journal: _Journal, written: list[str],
                    failed: list[dict[str, str]], not_moved: Optional[set[str]] = None) -> None:
    """Write one planned playlist (see :func:`apply_renames`); problems go to ``failed``."""
    from . import m3u  # local import: m3u imports this module

    path = pl.path
    info = {"src": str(path), "dst": ""}
    missing = [p for p in m3u.entry_paths(pl.lines, path.parent)
               if not _exists(p) or _fold(p) in (not_moved or ())]
    if missing:
        failed.append({**info, "error": f"disk not at its planned path: {missing[0].name}"})
        return
    text = m3u.content_of(pl.lines)
    data = text.encode("utf-8", errors="surrogateescape")
    existing: Optional[str] = None
    if _exists(path):
        existing = m3u.read_own_m3u_text(path)
        if existing is None:
            failed.append({**info, "error": "a file that is not a playlist of this app exists there"})
            return
    dseq = None
    if existing is not None:
        dseq = journal.record({"op": "delete", "path": _rel_str(path, root), "content": existing})
    cseq = journal.record({"op": "create", "path": _rel_str(path, root),
                           "sha1": hashlib.sha1(data).hexdigest(), "size": len(data)}, sync=True)
    try:
        m3u.write_playlist(path, text, replace_own=existing is not None)
    except (OSError, ValueError) as exc:
        journal.failed(cseq)
        if dseq is not None:
            journal.failed(dseq)
        failed.append({**info, "error": str(exc)})
        return
    journal.useful = True
    written.append(str(path))


def apply_renames(ops: Iterable[RenameOp], root: Path, progress: Optional[ProgressFn] = None,
                  dat_names: Iterable[str] = (), cancel: Any = None,
                  playlists: Sequence["m3u.M3UOp"] = ()) -> dict[str, Any]:
    """Perform the ``move`` and ``delete`` ops, then write the ``write`` ``playlists``.

    Returns ``{"moved", "renamed" (same number, legacy key), "deleted", "playlists_written", "failed":
    [{src, dst, error}], "removed_dirs": [..], "undo_log": path|None, "cancelled"}``.
    Playlists go in the same journal: an existing own file is journalled as ``delete`` (its content)
    first, then a ``create`` record (sha1 + size) *before* the file is written, so one undo removes
    what was created and restores what was replaced. A playlist whose disks are not all at their
    planned paths (a move failed) is skipped and reported in ``failed``.
    Every step is journalled before it happens. Ops blocked by a target that another
    op frees are retried in further passes; swap cycles are broken with a temporary
    name. ``cancel`` (callable or Event) stops between two steps. ``dat_names`` adds
    DAT folders that must never be removed (all known platform DATs are protected anyway).
    """
    root = Path(root)
    all_ops = list(ops)
    moves = [dataclasses.replace(op) for op in all_ops if op.status in MOVE_STATUSES]
    deletes = [op for op in all_ops if op.status == DELETE_STATUS]
    original: dict[int, Path] = {id(op): op.src for op in moves}
    writes = [p for p in playlists if p.status == "write"]
    total = len(moves) + len(deletes) + len(writes)
    journal = _Journal(root)
    written: list[str] = []
    done: list[dict[str, str]] = []
    deleted: list[str] = []
    failed: list[dict[str, str]] = []
    created: list[str] = []
    removed: list[str] = []
    cancelled = False

    def tick(name: str) -> None:
        if progress:
            progress(len(done) + len(deleted) + len(written) + len(failed), total, name)

    def move(op: RenameOp, src: Path, dst: Path) -> None:
        seq = journal.record({"op": "move", "src": _rel_str(src, root), "dst": _rel_str(dst, root)})
        try:
            _rename_no_overwrite(src, dst)
        except BaseException:
            journal.failed(seq)
            raise
        journal.useful = True

    error: Optional[str] = None
    try:
        pending = moves
        while pending and not cancelled:
            blocked: list[RenameOp] = []
            for op in pending:
                if _is_cancelled(cancel):
                    cancelled = True
                    break
                if _exists(op.dst) and not _same_file(op.src, op.dst) and _exists(op.src):
                    blocked.append(op)
                    continue
                try:
                    _make_dirs(op.dst.parent, created, journal)
                    move(op, op.src, op.dst)
                    done.append({"src": str(original[id(op)]), "dst": str(op.dst)})
                except UndoLogError:
                    raise
                except (OSError, ValueError) as exc:
                    failed.append({"src": str(original[id(op)]), "dst": str(op.dst), "error": str(exc)})
                tick(op.dst.name)
            if cancelled or not blocked:
                break
            if len(blocked) == len(pending):  # no progress: break a swap cycle, or give up
                member = _cycle_member(blocked)
                if member is None:
                    for op in blocked:
                        failed.append({"src": str(original[id(op)]), "dst": str(op.dst), "error": "target exists"})
                    break
                tmp = _temp_name(member.src)
                try:
                    move(member, member.src, tmp)
                    member.src = tmp
                except UndoLogError:
                    raise
                except (OSError, ValueError) as exc:
                    blocked.remove(member)
                    failed.append({"src": str(original[id(member)]), "dst": str(member.dst), "error": str(exc)})
            pending = blocked
        # A cycle member stuck at its temporary name goes back to where it was.
        for op in moves:
            if op.src != original[id(op)] and _exists(op.src):
                try:
                    move(op, op.src, original[id(op)])
                except (OSError, ValueError, UndoLogError):
                    pass

        if not cancelled:
            from . import m3u  # local import: m3u imports this module

            for op in deletes:
                if _is_cancelled(cancel):
                    cancelled = True
                    break
                try:
                    content = m3u.read_own_m3u_text(op.src)
                    if content is None:
                        raise ValueError("not a playlist made by simple-rom-organiser")
                    seq = journal.record({"op": "delete", "path": _rel_str(op.src, root), "content": content})
                    try:
                        os.unlink(op.src)
                    except BaseException:
                        journal.failed(seq)
                        raise
                    journal.useful = True
                    deleted.append(str(op.src))
                except UndoLogError:
                    raise
                except (OSError, ValueError) as exc:
                    failed.append({"src": str(op.src), "dst": "", "error": str(exc)})
                tick(op.src.name)

        if not cancelled:
            not_moved = {_fold(Path(f["dst"])) for f in failed if f.get("dst")}  # a move that did not happen
            for pl in writes:
                if _is_cancelled(cancel):
                    cancelled = True
                    break
                _write_playlist(pl, root, journal, written, failed, not_moved)
                tick(pl.path.name)

        protected = _protected_dirs(root, all_ops, dat_names)
        sources = ([Path(d["src"]).parent for d in done] + [Path(p).parent for p in deleted]
                   + [Path(c) for c in created])
        mine = set(created)
        for d in _remove_empty_dirs(sources, root, protected):
            if d in mine:  # a folder this apply created (move failed): not part of the old tree
                created.remove(d)
                mine.discard(d)
                journal.record({"op": "unmkdir", "path": _rel_str(Path(d), root)})
            else:
                journal.record({"op": "rmdir", "path": _rel_str(Path(d), root)})
                journal.useful = True
                removed.append(d)
    except UndoLogError as exc:  # stop: every change made so far is in the log
        error = str(exc)
    finally:
        log_path = journal.close()
    return {"moved": len(done), "renamed": len(done), "deleted": len(deleted),
            "playlists_written": len(written), "failed": failed,
            "removed_dirs": removed, "undo_log": str(log_path) if log_path else None,
            "cancelled": cancelled, "error": error}


# --------------------------------------------------------------------------- undo


def _restore_from_temp(src: Path) -> bool:
    """A case-only rename / cycle interrupted mid-way leaves ``<name>.romorg-tmp-xxxx``."""
    try:
        hits = [p for p in src.parent.iterdir() if p.name.startswith(src.name + TEMP_MARKER)]
    except OSError:
        return False
    if len(hits) != 1 or _exists(src):
        return False
    try:
        _move_exclusive(hits[0], src)
    except OSError:
        return False
    return True


def _file_matches(path: Path, size: int, sha1: str) -> bool:
    """True when ``path`` is a regular file of ``size`` bytes with this sha1."""
    try:
        if os.stat(path).st_size != size:
            return False
        h = hashlib.sha1()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
    except OSError:
        return False
    return h.hexdigest() == sha1.lower()


def undo(log_path: Path, root: Optional[Path] = None) -> dict[str, Any]:
    """Reverse the steps recorded in ``log_path`` (last first).

    Paths come from the log relative to its own folder (old absolute logs are
    rebased), and anything resolving outside that folder is refused. Recreates
    removed directories and deleted playlists, walks the moves and creates in reverse
    (restores moves; deletes files the apply created - e.g. Convert's clean copies -
    only if their size and sha1 are unchanged; result key ``created_removed``), deletes our own
    playlists that the restore made stale, then removes directories the apply
    created if they are empty. The log is renamed to ``*.undone`` when everything
    was restored; otherwise it is rewritten with what is left, so undo can be retried.
    ``root``, if given, must be the log's folder.
    """
    log_path = Path(log_path)
    base = log_path.parent.absolute()
    if root is not None and os.path.realpath(root) != os.path.realpath(base):
        raise ValueError("undo log is not in the selected folder")
    log = read_undo_log(log_path)

    dirs_restored = 0
    for p in sorted(log["removed_dirs"], key=lambda d: len(d.parts)):
        if not _exists(p):
            try:
                p.mkdir(parents=True, exist_ok=True)
                dirs_restored += 1
            except OSError:
                pass

    restored = 0
    created_removed = 0
    skipped: list[dict[str, str]] = []
    failed: list[dict[str, str]] = []
    remaining: list[dict[str, Any]] = []
    gone: set[str] = set()  # dst paths emptied by the restore
    for item in reversed(log["steps"]):
        if item.get("op") == "create":
            path = item["path"]
            info = {"src": "", "dst": str(path)}
            if not _exists(path):
                skipped.append({**info, "reason": "already gone"})
                continue
            if os.path.islink(path) or not _file_matches(path, item["size"], item["sha1"]):
                skipped.append({**info, "reason": "changed since it was created"})
                remaining.append(item)
                continue
            try:
                os.unlink(path)
                created_removed += 1
                gone.add(_fold(path))
            except OSError as exc:
                failed.append({**info, "error": str(exc)})
                remaining.append(item)
            continue
        src, dst = item["src"], item["dst"]
        info = {"src": str(src), "dst": str(dst)}
        if not _exists(dst):
            if _restore_from_temp(src):
                restored += 1
                continue
            reason = "already back in place" if _exists(src) else "moved file no longer exists"
            skipped.append({**info, "reason": reason})
            continue
        if _exists(src) and not _same_file(src, dst):
            skipped.append({**info, "reason": "original path is taken"})
            remaining.append(item)
            continue
        try:
            src.parent.mkdir(parents=True, exist_ok=True)
            _rename_no_overwrite(dst, src)
            restored += 1
            gone.add(_fold(dst))
        except OSError as exc:
            failed.append({**info, "error": str(exc)})
            remaining.append(item)

    from . import m3u  # local import: m3u imports this module

    m3us_restored = 0
    left_deleted: list[dict[str, Any]] = []
    for d in log["deleted"]:
        p, content = d["path"], d["content"]
        if p.suffix.lower() != ".m3u" or not content.startswith(m3u.M3U_MARKER):
            continue
        try:
            p.parent.mkdir(parents=True, exist_ok=True)
            with open(p, "x", encoding="utf-8", errors="surrogateescape", newline="\n") as f:
                f.write(content)
            m3us_restored += 1
        except FileExistsError:
            pass  # a newer playlist is there; keep it
        except OSError:
            left_deleted.append(d)

    # Partial output of an interrupted Convert (its original was restored above).
    temps_removed = 0
    left_temps: list[Path] = []
    for t in log["temp_files"]:
        try:
            if os.path.islink(t) or not t.is_file():
                continue  # gone (moved into place, or cleaned up by the run itself)
            os.unlink(t)
            temps_removed += 1
        except FileNotFoundError:
            pass
        except OSError:
            left_temps.append(t)

    # Our playlists that point at files the restore moved away are stale now.
    m3us_removed = 0
    if gone:
        changed = {_fold(item["path"]) for item in remaining if item.get("op") == "create"}  # user edited them
        for path in m3u.find_m3us(base):
            if _fold(path) in changed:
                continue
            info2 = m3u.read_m3u(path)
            if info2 and info2[0] and any(_fold(e) in gone for e in info2[1]):
                try:
                    os.unlink(path)
                    m3us_removed += 1
                except OSError:
                    pass

    dirs_removed = 0
    left_created: list[Path] = []
    for d in sorted(log["created_dirs"], key=lambda p: len(p.parts), reverse=True):
        try:
            os.rmdir(d)
            dirs_removed += 1
        except FileNotFoundError:
            pass
        except OSError:
            left_created.append(d)

    remaining.reverse()  # back to apply order
    if not remaining and not left_deleted and not left_temps:
        try:
            log_path.rename(log_path.with_name(log_path.name + UNDONE_SUFFIX))
        except OSError:
            pass
    else:
        try:
            _write_log(log_path, base, remaining, [d for d in left_created if _exists(d)], left_deleted,
                       left_temps)
        except (OSError, ValueError):
            pass
    return {"restored": restored, "skipped": skipped, "failed": failed, "remaining": len(remaining),
            "dirs_restored": dirs_restored, "dirs_removed": dirs_removed,
            "m3us_restored": m3us_restored, "m3us_removed": m3us_removed, "rejected": log["rejected"],
            "created_removed": created_removed, "temps_removed": temps_removed}


_LOG_RE = re.compile(re.escape(UNDO_PREFIX) + r".*\.json$")


def count_undo_log(log_path: Path) -> int:
    """How many changes an undo log holds (moves + created files), for display.

    Counts the records without building or checking their paths (``read_undo_log`` does that, and takes seconds on the
    log of a big library); records the real undo would reject as outside the folder are therefore counted too."""
    text = Path(log_path).read_text(encoding="utf-8")
    try:
        data = json.loads(text)
    except ValueError:
        data = None
    if isinstance(data, list):                                          # version 1
        return sum(1 for m in data if isinstance(m, dict))
    if isinstance(data, dict) and "moves" in data and data.get("version", 2) < 3:   # version 2
        return sum(1 for m in data.get("moves", []) if isinstance(m, dict))
    n = 0
    for line in text.splitlines():                                      # version 3: JSON lines
        if '"move"' not in line and '"create"' not in line:
            continue
        try:
            rec = json.loads(line)
        except ValueError:
            continue
        if isinstance(rec, dict) and rec.get("op") in ("move", "create"):
            n += 1
    return n


def list_undo_logs(root: Path) -> list[Path]:
    """Undo logs in ``root`` that have not been undone, newest first."""
    root = Path(root)
    try:
        logs = [p for p in root.iterdir() if p.is_file() and _LOG_RE.match(p.name)]
    except OSError:
        return []

    def key(p: Path) -> tuple[int, str]:
        try:
            return (p.stat().st_mtime_ns, p.name)
        except OSError:
            return (0, p.name)

    return sorted(logs, key=key, reverse=True)


# --------------------------------------------------------------------------- public aliases
# Building blocks shared with convert.py (same safety machinery as apply_renames).

Journal = _Journal
rename_no_overwrite = _rename_no_overwrite
move_exclusive = _move_exclusive
make_dirs = _make_dirs
temp_name = _temp_name
rel_str = _rel_str
remove_empty_dirs = _remove_empty_dirs
protected_dirs = _protected_dirs
